export const page1 = {
    "status": "ok",
    "status_message": "Query was successful",
    "data": {
    "movie_count": 13813,
    "limit": 20,
    "page_number": 1,
    "movies": [
    {
    "id": 3709,
    "url": "https://yts.lt/movie/the-shawshank-redemption-1994",
    "imdb_code": "tt0111161",
    "title": "The Shawshank Redemption",
    "title_english": "The Shawshank Redemption",
    "title_long": "The Shawshank Redemption (1994)",
    "slug": "the-shawshank-redemption-1994",
    "year": 1994,
    "rating": 9.3,
    "runtime": 142,
    "genres": [
    "Action",
    "Crime",
    "Drama"
    ],
    "summary": "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.",
    "description_full": "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.",
    "synopsis": "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.",
    "yt_trailer_code": "K_tLp7T6U1c",
    "language": "English",
    "mpa_rating": "R",
    "background_image": "https://yts.lt/assets/images/movies/The_Shawshank_Redemption_1994/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Shawshank_Redemption_1994/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Shawshank_Redemption_1994/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Shawshank_Redemption_1994/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Shawshank_Redemption_1994/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/AC418DB33FA5CEA4FAB11BC58008FE08F291C9BE",
    "hash": "AC418DB33FA5CEA4FAB11BC58008FE08F291C9BE",
    "quality": "720p",
    "type": "bluray",
    "seeds": 406,
    "peers": 101,
    "size": "848.96 MB",
    "size_bytes": 890199081,
    "date_uploaded": "2015-11-01 03:20:23",
    "date_uploaded_unix": 1446344423
    },
    {
    "url": "https://yts.lt/torrent/download/E0D00667650ABA9EE05AACBBBD8B55EA8A51F534",
    "hash": "E0D00667650ABA9EE05AACBBBD8B55EA8A51F534",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 209,
    "peers": 39,
    "size": "1.60 GB",
    "size_bytes": 1717986918,
    "date_uploaded": "2015-11-01 03:20:25",
    "date_uploaded_unix": 1446344425
    }
    ],
    "date_uploaded": "2015-11-01 03:20:23",
    "date_uploaded_unix": 1446344423
    },
    {
    "id": 3304,
    "url": "https://yts.lt/movie/the-godfather-1972",
    "imdb_code": "tt0068646",
    "title": "The Godfather",
    "title_english": "The Godfather",
    "title_long": "The Godfather (1972)",
    "slug": "the-godfather-1972",
    "year": 1972,
    "rating": 9.2,
    "runtime": 175,
    "genres": [
    "Action",
    "Crime",
    "Drama"
    ],
    "summary": "The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter's wedding. Michael, Vito's youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don's influence for the same, Vito refuses to do it. What follows is a clash between Vito's fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.",
    "description_full": "The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter's wedding. Michael, Vito's youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don's influence for the same, Vito refuses to do it. What follows is a clash between Vito's fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.",
    "synopsis": "The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter's wedding. Michael, Vito's youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don's influence for the same, Vito refuses to do it. What follows is a clash between Vito's fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.",
    "yt_trailer_code": "fBNpSRtfIUA",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/The_Godfather_1972/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Godfather_1972/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Godfather_1972/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Godfather_1972/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Godfather_1972/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/C168B84FC2B8CF062B67E4168E35C98F10BC7C74",
    "hash": "C168B84FC2B8CF062B67E4168E35C98F10BC7C74",
    "quality": "720p",
    "type": "bluray",
    "seeds": 256,
    "peers": 95,
    "size": "1.20 GB",
    "size_bytes": 1288490189,
    "date_uploaded": "2015-11-01 02:36:37",
    "date_uploaded_unix": 1446341797
    },
    {
    "url": "https://yts.lt/torrent/download/5E915039C619366E490D08DB3FFED21F3A3AE84A",
    "hash": "5E915039C619366E490D08DB3FFED21F3A3AE84A",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 624,
    "peers": 112,
    "size": "2.40 GB",
    "size_bytes": 2576980378,
    "date_uploaded": "2015-11-01 02:36:38",
    "date_uploaded_unix": 1446341798
    }
    ],
    "date_uploaded": "2015-11-01 02:36:37",
    "date_uploaded_unix": 1446341797
    },
    {
    "id": 10171,
    "url": "https://yts.lt/movie/the-colour-of-darkness-2017",
    "imdb_code": "tt5717184",
    "title": "The Colour of Darkness",
    "title_english": "The Colour of Darkness",
    "title_long": "The Colour of Darkness (2017)",
    "slug": "the-colour-of-darkness-2017",
    "year": 2017,
    "rating": 9.2,
    "runtime": 0,
    "genres": [
    "Drama"
    ],
    "summary": "All the colour, depth and mystery of India's complex and riotous cultural heritage is brought to light in a single action which changes two countries forever. A proud Indian international student is attacked in a brightly lit train carriage against a backdrop of darkness. Unknown to his attackers his high caste status has little relevance, and in one poignant moment, he is rescued by his counterpart, an 'untouchable', a low caste. They are united by what would otherwise be impossible. The highly publicised event sends shock waves through the international community. As the climate escalates, Maria Kris a young Australian journalist of Indian descent is sent to investigate, and what happens from there uncovers long established and inherent prejudices between the two countries and what lies between .... In her quest for truth, she meets a young Indian student Giriraj, who changes her life forever through an unlikely meeting. Throughout their ensuing friendship, Maria is taken by Giriraj...",
    "description_full": "All the colour, depth and mystery of India's complex and riotous cultural heritage is brought to light in a single action which changes two countries forever. A proud Indian international student is attacked in a brightly lit train carriage against a backdrop of darkness. Unknown to his attackers his high caste status has little relevance, and in one poignant moment, he is rescued by his counterpart, an 'untouchable', a low caste. They are united by what would otherwise be impossible. The highly publicised event sends shock waves through the international community. As the climate escalates, Maria Kris a young Australian journalist of Indian descent is sent to investigate, and what happens from there uncovers long established and inherent prejudices between the two countries and what lies between .... In her quest for truth, she meets a young Indian student Giriraj, who changes her life forever through an unlikely meeting. Throughout their ensuing friendship, Maria is taken by Giriraj...",
    "synopsis": "All the colour, depth and mystery of India's complex and riotous cultural heritage is brought to light in a single action which changes two countries forever. A proud Indian international student is attacked in a brightly lit train carriage against a backdrop of darkness. Unknown to his attackers his high caste status has little relevance, and in one poignant moment, he is rescued by his counterpart, an 'untouchable', a low caste. They are united by what would otherwise be impossible. The highly publicised event sends shock waves through the international community. As the climate escalates, Maria Kris a young Australian journalist of Indian descent is sent to investigate, and what happens from there uncovers long established and inherent prejudices between the two countries and what lies between .... In her quest for truth, she meets a young Indian student Giriraj, who changes her life forever through an unlikely meeting. Throughout their ensuing friendship, Maria is taken by Giriraj...",
    "yt_trailer_code": "5g-ezea3zKg",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/the_colour_of_darkness_2017/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/the_colour_of_darkness_2017/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/the_colour_of_darkness_2017/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/the_colour_of_darkness_2017/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/the_colour_of_darkness_2017/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/CCC408214A13053823BB617BBC28A3CC4558C829",
    "hash": "CCC408214A13053823BB617BBC28A3CC4558C829",
    "quality": "720p",
    "type": "web",
    "seeds": 10,
    "peers": 7,
    "size": "1.11 GB",
    "size_bytes": 1191853425,
    "date_uploaded": "2018-12-15 07:42:20",
    "date_uploaded_unix": 1544856140
    },
    {
    "url": "https://yts.lt/torrent/download/2968027A4BBFF2F14D993C16C5C43CA7C2476591",
    "hash": "2968027A4BBFF2F14D993C16C5C43CA7C2476591",
    "quality": "1080p",
    "type": "web",
    "seeds": 12,
    "peers": 5,
    "size": "2.14 GB",
    "size_bytes": 2297807503,
    "date_uploaded": "2018-12-15 09:52:21",
    "date_uploaded_unix": 1544863941
    }
    ],
    "date_uploaded": "2018-12-15 07:42:20",
    "date_uploaded_unix": 1544856140
    },
    {
    "id": 9717,
    "url": "https://yts.lt/movie/natsamrat-2016",
    "imdb_code": "tt5311546",
    "title": "Natsamrat",
    "title_english": "Natsamrat",
    "title_long": "Natsamrat (2016)",
    "slug": "natsamrat-2016",
    "year": 2016,
    "rating": 9.1,
    "runtime": 0,
    "genres": [
    "Action",
    "Drama",
    "Family"
    ],
    "summary": "The film is a tragedy about a veteran theatre actor named Ganpat \"Appa\" Belwalkar (Nana Patekar) who has been the best of his lot during his heyday, garnering fame and fortune acting in plays based on various works, especially William Shakespeare's. It is a tragedy of a veteran actor who enjoyed a very vital importance in his life but who becomes the victim of old age alienation and estrangement. The film reveals an intensely tragic fate of an actor who becomes victim of fate and fortune in old age, which is similar to the fate of Lear. Natsamrat suffers the pangs of old age and dishonor inflicted on him by his own children. It is a tragedy of great humanist and actor who succumbs to the ill fate and destiny. In fact, Natsamrat is a story of Ganpatrao Belvalkar, who withstands great suffering after his retirement from stage acting.",
    "description_full": "The film is a tragedy about a veteran theatre actor named Ganpat \"Appa\" Belwalkar (Nana Patekar) who has been the best of his lot during his heyday, garnering fame and fortune acting in plays based on various works, especially William Shakespeare's. It is a tragedy of a veteran actor who enjoyed a very vital importance in his life but who becomes the victim of old age alienation and estrangement. The film reveals an intensely tragic fate of an actor who becomes victim of fate and fortune in old age, which is similar to the fate of Lear. Natsamrat suffers the pangs of old age and dishonor inflicted on him by his own children. It is a tragedy of great humanist and actor who succumbs to the ill fate and destiny. In fact, Natsamrat is a story of Ganpatrao Belvalkar, who withstands great suffering after his retirement from stage acting.",
    "synopsis": "The film is a tragedy about a veteran theatre actor named Ganpat \"Appa\" Belwalkar (Nana Patekar) who has been the best of his lot during his heyday, garnering fame and fortune acting in plays based on various works, especially William Shakespeare's. It is a tragedy of a veteran actor who enjoyed a very vital importance in his life but who becomes the victim of old age alienation and estrangement. The film reveals an intensely tragic fate of an actor who becomes victim of fate and fortune in old age, which is similar to the fate of Lear. Natsamrat suffers the pangs of old age and dishonor inflicted on him by his own children. It is a tragedy of great humanist and actor who succumbs to the ill fate and destiny. In fact, Natsamrat is a story of Ganpatrao Belvalkar, who withstands great suffering after his retirement from stage acting.",
    "yt_trailer_code": "DCXDyIsPEN8",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/natsamrat_2016/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/natsamrat_2016/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/natsamrat_2016/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/natsamrat_2016/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/natsamrat_2016/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/9C2440F9D38F769B768660FE715D36572776F681",
    "hash": "9C2440F9D38F769B768660FE715D36572776F681",
    "quality": "720p",
    "type": "web",
    "seeds": 23,
    "peers": 13,
    "size": "1.37 GB",
    "size_bytes": 1471026299,
    "date_uploaded": "2018-11-12 08:18:51",
    "date_uploaded_unix": 1542007131
    },
    {
    "url": "https://yts.lt/torrent/download/5ACEB9A75BD576A15EDA44E196E6569F052AA28D",
    "hash": "5ACEB9A75BD576A15EDA44E196E6569F052AA28D",
    "quality": "1080p",
    "type": "web",
    "seeds": 34,
    "peers": 1,
    "size": "2.64 GB",
    "size_bytes": 2834678415,
    "date_uploaded": "2018-11-12 10:38:01",
    "date_uploaded_unix": 1542015481
    }
    ],
    "date_uploaded": "2018-11-12 08:18:51",
    "date_uploaded_unix": 1542007131
    },
    {
    "id": 3175,
    "url": "https://yts.lt/movie/the-dark-knight-2008",
    "imdb_code": "tt0468569",
    "title": "The Dark Knight",
    "title_english": "The Dark Knight",
    "title_long": "The Dark Knight (2008)",
    "slug": "the-dark-knight-2008",
    "year": 2008,
    "rating": 9,
    "runtime": 152,
    "genres": [
    "Action",
    "Adventure",
    "Crime",
    "Drama",
    "Thriller"
    ],
    "summary": "Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as \"The Joker\" appears in Gotham, creating a new wave of chaos. Batman's struggle against The Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.",
    "description_full": "Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as \"The Joker\" appears in Gotham, creating a new wave of chaos. Batman's struggle against The Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.",
    "synopsis": "Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as \"The Joker\" appears in Gotham, creating a new wave of chaos. Batman's struggle against The Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.",
    "yt_trailer_code": "kmJLuwP3MbY",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/The_Dark_Knight_2008/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Dark_Knight_2008/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Dark_Knight_2008/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Dark_Knight_2008/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Dark_Knight_2008/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/F5D61BF3D57082BA2EE1305DA5DF8DCD10D34539",
    "hash": "F5D61BF3D57082BA2EE1305DA5DF8DCD10D34539",
    "quality": "720p",
    "type": "bluray",
    "seeds": 180,
    "peers": 70,
    "size": "949.99 MB",
    "size_bytes": 996136714,
    "date_uploaded": "2015-11-01 02:20:06",
    "date_uploaded_unix": 1446340806
    },
    {
    "url": "https://yts.lt/torrent/download/A54926C2E07B0E5F0243954330B599B31C804F0B",
    "hash": "A54926C2E07B0E5F0243954330B599B31C804F0B",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 1241,
    "peers": 198,
    "size": "1.70 GB",
    "size_bytes": 1825361101,
    "date_uploaded": "2015-11-01 02:20:12",
    "date_uploaded_unix": 1446340812
    }
    ],
    "date_uploaded": "2015-11-01 02:20:06",
    "date_uploaded_unix": 1446340806
    },
    {
    "id": 3305,
    "url": "https://yts.lt/movie/the-godfather-part-ii-1974",
    "imdb_code": "tt0071562",
    "title": "The Godfather: Part II",
    "title_english": "The Godfather: Part II",
    "title_long": "The Godfather: Part II (1974)",
    "slug": "the-godfather-part-ii-1974",
    "year": 1974,
    "rating": 9,
    "runtime": 202,
    "genres": [
    "Action",
    "Crime",
    "Drama"
    ],
    "summary": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    "description_full": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    "synopsis": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    "yt_trailer_code": "9O1Iy9od7-A",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/The_Godfather_Part_II_1974/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Godfather_Part_II_1974/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Godfather_Part_II_1974/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Godfather_Part_II_1974/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Godfather_Part_II_1974/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/B27022D09BC067D46BBDB65AE62348AB3F21C727",
    "hash": "B27022D09BC067D46BBDB65AE62348AB3F21C727",
    "quality": "720p",
    "type": "bluray",
    "seeds": 321,
    "peers": 53,
    "size": "1.30 GB",
    "size_bytes": 1395864371,
    "date_uploaded": "2015-11-01 02:36:45",
    "date_uploaded_unix": 1446341805
    },
    {
    "url": "https://yts.lt/torrent/download/6C9124FE9A99B2001FAD76A76152691BC515A80D",
    "hash": "6C9124FE9A99B2001FAD76A76152691BC515A80D",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 184,
    "peers": 51,
    "size": "2.70 GB",
    "size_bytes": 2899102925,
    "date_uploaded": "2015-11-01 02:36:50",
    "date_uploaded_unix": 1446341810
    }
    ],
    "date_uploaded": "2015-11-01 02:36:45",
    "date_uploaded_unix": 1446341805
    },
    {
    "id": 7893,
    "url": "https://yts.lt/movie/the-mountain-ii-2016",
    "imdb_code": "tt5813916",
    "title": "The Mountain II",
    "title_english": "The Mountain II",
    "title_long": "The Mountain II (2016)",
    "slug": "the-mountain-ii-2016",
    "year": 2016,
    "rating": 9,
    "runtime": 135,
    "genres": [
    "Action",
    "Drama",
    "War"
    ],
    "summary": "DAG II; tells the story of a clandestine special forces squad; call sign 'Storm Bringer'. Following the events of the first film, Bekir and Oguz, unlikely best friends, have enrolled in the world famous, perpetually grueling Turkish special forces training. Their first mission begins six years later-- to infiltrate the most barbarous area of modern day Iraq for a rescue mission.",
    "description_full": "DAG II; tells the story of a clandestine special forces squad; call sign 'Storm Bringer'. Following the events of the first film, Bekir and Oguz, unlikely best friends, have enrolled in the world famous, perpetually grueling Turkish special forces training. Their first mission begins six years later-- to infiltrate the most barbarous area of modern day Iraq for a rescue mission.",
    "synopsis": "DAG II; tells the story of a clandestine special forces squad; call sign 'Storm Bringer'. Following the events of the first film, Bekir and Oguz, unlikely best friends, have enrolled in the world famous, perpetually grueling Turkish special forces training. Their first mission begins six years later-- to infiltrate the most barbarous area of modern day Iraq for a rescue mission.",
    "yt_trailer_code": "yBn2MfVmkKI",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/the_mountain_ii_2016/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/the_mountain_ii_2016/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/the_mountain_ii_2016/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/the_mountain_ii_2016/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/the_mountain_ii_2016/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/010CCD66B5FE171CEA435DB40E7D02F317E80AC8",
    "hash": "010CCD66B5FE171CEA435DB40E7D02F317E80AC8",
    "quality": "720p",
    "type": "web",
    "seeds": 110,
    "peers": 26,
    "size": "1.11 GB",
    "size_bytes": 1191853425,
    "date_uploaded": "2018-05-28 21:41:29",
    "date_uploaded_unix": 1527536489
    },
    {
    "url": "https://yts.lt/torrent/download/317685A3FE74A9B36EE13D45D864196620FAA292",
    "hash": "317685A3FE74A9B36EE13D45D864196620FAA292",
    "quality": "1080p",
    "type": "web",
    "seeds": 137,
    "peers": 28,
    "size": "2.14 GB",
    "size_bytes": 2297807503,
    "date_uploaded": "2018-05-28 23:39:15",
    "date_uploaded_unix": 1527543555
    }
    ],
    "date_uploaded": "2018-05-28 21:41:29",
    "date_uploaded_unix": 1527536489
    },
    {
    "id": 2429,
    "url": "https://yts.lt/movie/pulp-fiction-1994",
    "imdb_code": "tt0110912",
    "title": "Pulp Fiction",
    "title_english": "Pulp Fiction",
    "title_long": "Pulp Fiction (1994)",
    "slug": "pulp-fiction-1994",
    "year": 1994,
    "rating": 8.9,
    "runtime": 154,
    "genres": [
    "Action",
    "Crime",
    "Drama"
    ],
    "summary": "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
    "description_full": "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
    "synopsis": "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
    "yt_trailer_code": "tGpTpVyI_OQ",
    "language": "English",
    "mpa_rating": "R",
    "background_image": "https://yts.lt/assets/images/movies/Pulp_Fiction_1994/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Pulp_Fiction_1994/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Pulp_Fiction_1994/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Pulp_Fiction_1994/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Pulp_Fiction_1994/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/D55F1E840F1BD6576EAD67A4D04E5D6EA294414B",
    "hash": "D55F1E840F1BD6576EAD67A4D04E5D6EA294414B",
    "quality": "720p",
    "type": "bluray",
    "seeds": 330,
    "peers": 48,
    "size": "751.29 MB",
    "size_bytes": 787784663,
    "date_uploaded": "2015-11-01 01:52:11",
    "date_uploaded_unix": 1446339131
    },
    {
    "url": "https://yts.lt/torrent/download/3F8F219568B8B229581DDDD7BC5A5E889E906A9B",
    "hash": "3F8F219568B8B229581DDDD7BC5A5E889E906A9B",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 481,
    "peers": 89,
    "size": "1.40 GB",
    "size_bytes": 1503238554,
    "date_uploaded": "2015-11-01 01:52:15",
    "date_uploaded_unix": 1446339135
    }
    ],
    "date_uploaded": "2015-11-01 01:52:11",
    "date_uploaded_unix": 1446339131
    },
    {
    "id": 2640,
    "url": "https://yts.lt/movie/schindlers-list-1993",
    "imdb_code": "tt0108052",
    "title": "Schindler's List",
    "title_english": "Schindler's List",
    "title_long": "Schindler's List (1993)",
    "slug": "schindlers-list-1993",
    "year": 1993,
    "rating": 8.9,
    "runtime": 195,
    "genres": [
    "Action",
    "Biography",
    "Drama",
    "History"
    ],
    "summary": "Oskar Schindler is a vainglorious and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.",
    "description_full": "Oskar Schindler is a vainglorious and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.",
    "synopsis": "Oskar Schindler is a vainglorious and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.",
    "yt_trailer_code": "bJcLRFWxRno",
    "language": "English",
    "mpa_rating": "R",
    "background_image": "https://yts.lt/assets/images/movies/Schindlers_List_1993/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Schindlers_List_1993/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Schindlers_List_1993/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Schindlers_List_1993/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Schindlers_List_1993/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/69B6CF5AD84C75E257A0597F827E1F032BA831BF",
    "hash": "69B6CF5AD84C75E257A0597F827E1F032BA831BF",
    "quality": "720p",
    "type": "bluray",
    "seeds": 177,
    "peers": 28,
    "size": "1.20 GB",
    "size_bytes": 1288490189,
    "date_uploaded": "2015-11-01 01:16:11",
    "date_uploaded_unix": 1446336971
    },
    {
    "url": "https://yts.lt/torrent/download/F64C844C39FCD6A5F9157884E97296F7019DB83B",
    "hash": "F64C844C39FCD6A5F9157884E97296F7019DB83B",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 87,
    "peers": 16,
    "size": "2.50 GB",
    "size_bytes": 2684354560,
    "date_uploaded": "2015-11-01 01:16:14",
    "date_uploaded_unix": 1446336974
    }
    ],
    "date_uploaded": "2015-11-01 01:16:11",
    "date_uploaded_unix": 1446336971
    },
    {
    "id": 3489,
    "url": "https://yts.lt/movie/the-lord-of-the-rings-the-return-of-the-king-2003",
    "imdb_code": "tt0167260",
    "title": "The Lord of the Rings: The Return of the King",
    "title_english": "The Lord of the Rings: The Return of the King",
    "title_long": "The Lord of the Rings: The Return of the King (2003)",
    "slug": "the-lord-of-the-rings-the-return-of-the-king-2003",
    "year": 2003,
    "rating": 8.9,
    "runtime": 201,
    "genres": [
    "Action",
    "Adventure",
    "Drama",
    "Fantasy"
    ],
    "summary": "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.",
    "description_full": "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.",
    "synopsis": "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.",
    "yt_trailer_code": "co9SNfJNDN8",
    "language": "English",
    "mpa_rating": "PG-13",
    "background_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Return_of_the_King_EXTENDED_2003/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/FDF8D3EB9CD78DE60C3CBB3B68AF6C8A7D560E67",
    "hash": "FDF8D3EB9CD78DE60C3CBB3B68AF6C8A7D560E67",
    "quality": "720p",
    "type": "bluray",
    "seeds": 91,
    "peers": 34,
    "size": "1.70 GB",
    "size_bytes": 1825361101,
    "date_uploaded": "2015-11-01 02:58:16",
    "date_uploaded_unix": 1446343096
    },
    {
    "url": "https://yts.lt/torrent/download/AD73D5576DC4ECFEEA4353D4503F9B3F93DFA740",
    "hash": "AD73D5576DC4ECFEEA4353D4503F9B3F93DFA740",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 587,
    "peers": 170,
    "size": "3.70 GB",
    "size_bytes": 3972844749,
    "date_uploaded": "2015-11-01 02:58:18",
    "date_uploaded_unix": 1446343098
    }
    ],
    "date_uploaded": "2015-11-01 02:58:16",
    "date_uploaded_unix": 1446343096
    },
    {
    "id": 4253,
    "url": "https://yts.lt/movie/12-angry-men-1957",
    "imdb_code": "tt0050083",
    "title": "12 Angry Men",
    "title_english": "12 Angry Men",
    "title_long": "12 Angry Men (1957)",
    "slug": "12-angry-men-1957",
    "year": 1957,
    "rating": 8.9,
    "runtime": 96,
    "genres": [
    "Action",
    "Crime",
    "Drama"
    ],
    "summary": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other. Based on the play, all of the action takes place on the stage of the jury room.",
    "description_full": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other. Based on the play, all of the action takes place on the stage of the jury room.",
    "synopsis": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other. Based on the play, all of the action takes place on the stage of the jury room.",
    "yt_trailer_code": "OvebOqneLIU",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/12_Angry_Men_1957/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/12_Angry_Men_1957/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/12_Angry_Men_1957/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/12_Angry_Men_1957/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/12_Angry_Men_1957/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/A303CAA20F46AAB9BBE75DA62B90E375FA03578A",
    "hash": "A303CAA20F46AAB9BBE75DA62B90E375FA03578A",
    "quality": "720p",
    "type": "bluray",
    "seeds": 158,
    "peers": 19,
    "size": "700.07 MB",
    "size_bytes": 734076600,
    "date_uploaded": "2015-10-31 20:46:02",
    "date_uploaded_unix": 1446320762
    },
    {
    "url": "https://yts.lt/torrent/download/4DB3FDD949B99781E6AB1979BA476EC3E932970C",
    "hash": "4DB3FDD949B99781E6AB1979BA476EC3E932970C",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 70,
    "peers": 17,
    "size": "1.52 GB",
    "size_bytes": 1632087572,
    "date_uploaded": "2018-04-28 02:11:22",
    "date_uploaded_unix": 1524874282
    }
    ],
    "date_uploaded": "2015-10-31 20:46:02",
    "date_uploaded_unix": 1446320762
    },
    {
    "id": 1151,
    "url": "https://yts.lt/movie/fight-club-1999",
    "imdb_code": "tt0137523",
    "title": "Fight Club",
    "title_english": "Fight Club",
    "title_long": "Fight Club (1999)",
    "slug": "fight-club-1999",
    "year": 1999,
    "rating": 8.8,
    "runtime": 139,
    "genres": [
    "Action",
    "Drama"
    ],
    "summary": "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler's fight club, he must accept the awful truth that Tyler may not be who he says he is.",
    "description_full": "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler's fight club, he must accept the awful truth that Tyler may not be who he says he is.",
    "synopsis": "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler's fight club, he must accept the awful truth that Tyler may not be who he says he is.",
    "yt_trailer_code": "BdJKm16Co6M",
    "language": "English",
    "mpa_rating": "R",
    "background_image": "https://yts.lt/assets/images/movies/Fight_Club_1999/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Fight_Club_1999/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Fight_Club_1999/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Fight_Club_1999/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Fight_Club_1999/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/4B37249E7F82F60D94C7A15B743A6B624E640372",
    "hash": "4B37249E7F82F60D94C7A15B743A6B624E640372",
    "quality": "720p",
    "type": "bluray",
    "seeds": 202,
    "peers": 59,
    "size": "1.00 GB",
    "size_bytes": 1073741824,
    "date_uploaded": "2015-10-31 23:25:31",
    "date_uploaded_unix": 1446330331
    },
    {
    "url": "https://yts.lt/torrent/download/A086CE4AFABBD8AB949662E30134A49E22D1F0C7",
    "hash": "A086CE4AFABBD8AB949662E30134A49E22D1F0C7",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 654,
    "peers": 103,
    "size": "1.85 GB",
    "size_bytes": 1986422374,
    "date_uploaded": "2015-10-31 23:25:32",
    "date_uploaded_unix": 1446330332
    }
    ],
    "date_uploaded": "2015-10-31 23:25:31",
    "date_uploaded_unix": 1446330331
    },
    {
    "id": 1208,
    "url": "https://yts.lt/movie/forrest-gump-1994",
    "imdb_code": "tt0109830",
    "title": "Forrest Gump",
    "title_english": "Forrest Gump",
    "title_long": "Forrest Gump (1994)",
    "slug": "forrest-gump-1994",
    "year": 1994,
    "rating": 8.8,
    "runtime": 142,
    "genres": [
    "Action",
    "Comedy",
    "Drama",
    "Romance"
    ],
    "summary": "Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His 'mama' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.",
    "description_full": "Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His 'mama' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.",
    "synopsis": "Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His 'mama' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.",
    "yt_trailer_code": "VVN82P8dN7I",
    "language": "English",
    "mpa_rating": "PG-13",
    "background_image": "https://yts.lt/assets/images/movies/Forrest_Gump_1994/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Forrest_Gump_1994/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Forrest_Gump_1994/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Forrest_Gump_1994/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Forrest_Gump_1994/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/9BFB78F3CDD5E7CFC3FD2A5CDDDB1E86DA43D345",
    "hash": "9BFB78F3CDD5E7CFC3FD2A5CDDDB1E86DA43D345",
    "quality": "720p",
    "type": "bluray",
    "seeds": 285,
    "peers": 54,
    "size": "852.02 MB",
    "size_bytes": 893407724,
    "date_uploaded": "2015-10-31 23:30:05",
    "date_uploaded_unix": 1446330605
    },
    {
    "url": "https://yts.lt/torrent/download/FEE625A78CB2057CE7845AA66E95F60D43EA8AB0",
    "hash": "FEE625A78CB2057CE7845AA66E95F60D43EA8AB0",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 112,
    "peers": 26,
    "size": "1.90 GB",
    "size_bytes": 2040109466,
    "date_uploaded": "2015-10-31 23:30:08",
    "date_uploaded_unix": 1446330608
    }
    ],
    "date_uploaded": "2015-10-31 23:30:05",
    "date_uploaded_unix": 1446330605
    },
    {
    "id": 1606,
    "url": "https://yts.lt/movie/inception-2010",
    "imdb_code": "tt1375666",
    "title": "Inception",
    "title_english": "Inception",
    "title_long": "Inception (2010)",
    "slug": "inception-2010",
    "year": 2010,
    "rating": 8.8,
    "runtime": 148,
    "genres": [
    "Action",
    "Adventure",
    "Crime",
    "Mystery",
    "Sci-Fi",
    "Thriller"
    ],
    "summary": "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.",
    "description_full": "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.",
    "synopsis": "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.",
    "yt_trailer_code": "xitHF0IPJSQ",
    "language": "English",
    "mpa_rating": "PG-13",
    "background_image": "https://yts.lt/assets/images/movies/Inception_2010/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Inception_2010/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Inception_2010/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Inception_2010/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Inception_2010/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/CE9156EB497762F8B7577B71C0647A4B0C3423E1",
    "hash": "CE9156EB497762F8B7577B71C0647A4B0C3423E1",
    "quality": "720p",
    "type": "bluray",
    "seeds": 327,
    "peers": 65,
    "size": "1.07 GB",
    "size_bytes": 1148903752,
    "date_uploaded": "2015-11-01 00:14:37",
    "date_uploaded_unix": 1446333277
    },
    {
    "url": "https://yts.lt/torrent/download/224BF45881252643DFC2E71ABC7B2660A21C68C4",
    "hash": "224BF45881252643DFC2E71ABC7B2660A21C68C4",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 707,
    "peers": 130,
    "size": "1.85 GB",
    "size_bytes": 1986422374,
    "date_uploaded": "2015-11-01 00:14:39",
    "date_uploaded_unix": 1446333279
    }
    ],
    "date_uploaded": "2015-11-01 00:14:37",
    "date_uploaded_unix": 1446333277
    },
    {
    "id": 6618,
    "url": "https://yts.lt/movie/the-phantom-of-the-opera-at-the-royal-albert-hall-2011",
    "imdb_code": "tt2077886",
    "title": "The Phantom of the Opera at the Royal Albert Hall",
    "title_english": "The Phantom of the Opera at the Royal Albert Hall",
    "title_long": "The Phantom of the Opera at the Royal Albert Hall (2011)",
    "slug": "the-phantom-of-the-opera-at-the-royal-albert-hall-2011",
    "year": 2011,
    "rating": 8.8,
    "runtime": 137,
    "genres": [
    "Action",
    "Drama",
    "Music",
    "Musical",
    "Romance",
    "Thriller"
    ],
    "summary": "In 1986, Andrew Lloyd Webber's The Phantom of the Opera arrived on the West End stage at Her Majesty's Theatre. Fast forward 25 years and Phantom has achieved global success, millions of viewers, a film adaptation in 2004 and a musical sequel. Now viewers have the chance to experience this phenomenal show right from their own screens. Filmed at the Royal Albert Hall, this stunning performance brings the show to a bigger stage and celebrates its role as one of the biggest shows in theatre history, with speeches, performances and appearances by the original cast and some of the show's most notable Phantoms, including John Owen-Jones and Colm Wilkinson. Starring Ramin Karimloo and Sierra Boggess, Phantom tells the story of a deformed musical genius who lives in the catacombs of the Paris Opera House. Shunned by society, the Phantom seeks revenge in cruel and often violent acts. The Phantom is in love with chorus girl Christine Daaé and has been secretly training her to replace La ...",
    "description_full": "In 1986, Andrew Lloyd Webber's The Phantom of the Opera arrived on the West End stage at Her Majesty's Theatre. Fast forward 25 years and Phantom has achieved global success, millions of viewers, a film adaptation in 2004 and a musical sequel. Now viewers have the chance to experience this phenomenal show right from their own screens. Filmed at the Royal Albert Hall, this stunning performance brings the show to a bigger stage and celebrates its role as one of the biggest shows in theatre history, with speeches, performances and appearances by the original cast and some of the show's most notable Phantoms, including John Owen-Jones and Colm Wilkinson. Starring Ramin Karimloo and Sierra Boggess, Phantom tells the story of a deformed musical genius who lives in the catacombs of the Paris Opera House. Shunned by society, the Phantom seeks revenge in cruel and often violent acts. The Phantom is in love with chorus girl Christine Daaé and has been secretly training her to replace La ...",
    "synopsis": "In 1986, Andrew Lloyd Webber's The Phantom of the Opera arrived on the West End stage at Her Majesty's Theatre. Fast forward 25 years and Phantom has achieved global success, millions of viewers, a film adaptation in 2004 and a musical sequel. Now viewers have the chance to experience this phenomenal show right from their own screens. Filmed at the Royal Albert Hall, this stunning performance brings the show to a bigger stage and celebrates its role as one of the biggest shows in theatre history, with speeches, performances and appearances by the original cast and some of the show's most notable Phantoms, including John Owen-Jones and Colm Wilkinson. Starring Ramin Karimloo and Sierra Boggess, Phantom tells the story of a deformed musical genius who lives in the catacombs of the Paris Opera House. Shunned by society, the Phantom seeks revenge in cruel and often violent acts. The Phantom is in love with chorus girl Christine Daaé and has been secretly training her to replace La ...",
    "yt_trailer_code": "b88070kuP4w",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/the_phantom_of_the_opera_at_the_royal_albert_hall_2011/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/the_phantom_of_the_opera_at_the_royal_albert_hall_2011/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/the_phantom_of_the_opera_at_the_royal_albert_hall_2011/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/the_phantom_of_the_opera_at_the_royal_albert_hall_2011/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/the_phantom_of_the_opera_at_the_royal_albert_hall_2011/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/829F303AF3D9D0DA472DAA40DC2E83A8917A8877",
    "hash": "829F303AF3D9D0DA472DAA40DC2E83A8917A8877",
    "quality": "720p",
    "type": "bluray",
    "seeds": 26,
    "peers": 8,
    "size": "1.15 GB",
    "size_bytes": 1234803098,
    "date_uploaded": "2017-07-08 05:35:36",
    "date_uploaded_unix": 1499484936
    },
    {
    "url": "https://yts.lt/torrent/download/BD4544A9B63D2B2EF36F6A2FE1770DF17F686592",
    "hash": "BD4544A9B63D2B2EF36F6A2FE1770DF17F686592",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 34,
    "peers": 9,
    "size": "2.44 GB",
    "size_bytes": 2619930051,
    "date_uploaded": "2017-07-08 09:09:34",
    "date_uploaded_unix": 1499497774
    }
    ],
    "date_uploaded": "2017-07-08 05:35:36",
    "date_uploaded_unix": 1499484936
    },
    {
    "id": 3313,
    "url": "https://yts.lt/movie/the-good-the-bad-and-the-ugly-1966",
    "imdb_code": "tt0060196",
    "title": "The Good, the Bad and the Ugly",
    "title_english": "The Good, the Bad and the Ugly",
    "title_long": "The Good, the Bad and the Ugly (1966)",
    "slug": "the-good-the-bad-and-the-ugly-1966",
    "year": 1966,
    "rating": 8.8,
    "runtime": 161,
    "genres": [
    "Action",
    "Western"
    ],
    "summary": "Blondie (The Good) (Clint Eastwood) is a professional gunslinger who is out trying to earn a few dollars. Angel Eyes (The Bad) (Lee Van Cleef) is a hitman who always commits to a task and sees it through, as long as he is paid to do so. And Tuco (The Ugly) (Eli Wallach) is a wanted outlaw trying to take care of his own hide. Tuco and Blondie share a partnership together making money off of Tuco's bounty, but when Blondie unties the partnership, Tuco tries to hunt down Blondie. When Blondie and Tuco come across a horse carriage loaded with dead bodies, they soon learn from the only survivor, Bill Carson (Antonio Casale), that he and a few other men have buried a stash of gold in a cemetery. Unfortunately, Carson dies and Tuco only finds out the name of the cemetery, while Blondie finds out the name on the grave. Now the two must keep each other alive in order to find the gold. Angel Eyes (who had been looking for Bill Carson) discovers that Tuco and Blondie met with Carson and knows ...",
    "description_full": "Blondie (The Good) (Clint Eastwood) is a professional gunslinger who is out trying to earn a few dollars. Angel Eyes (The Bad) (Lee Van Cleef) is a hitman who always commits to a task and sees it through, as long as he is paid to do so. And Tuco (The Ugly) (Eli Wallach) is a wanted outlaw trying to take care of his own hide. Tuco and Blondie share a partnership together making money off of Tuco's bounty, but when Blondie unties the partnership, Tuco tries to hunt down Blondie. When Blondie and Tuco come across a horse carriage loaded with dead bodies, they soon learn from the only survivor, Bill Carson (Antonio Casale), that he and a few other men have buried a stash of gold in a cemetery. Unfortunately, Carson dies and Tuco only finds out the name of the cemetery, while Blondie finds out the name on the grave. Now the two must keep each other alive in order to find the gold. Angel Eyes (who had been looking for Bill Carson) discovers that Tuco and Blondie met with Carson and knows ...",
    "synopsis": "Blondie (The Good) (Clint Eastwood) is a professional gunslinger who is out trying to earn a few dollars. Angel Eyes (The Bad) (Lee Van Cleef) is a hitman who always commits to a task and sees it through, as long as he is paid to do so. And Tuco (The Ugly) (Eli Wallach) is a wanted outlaw trying to take care of his own hide. Tuco and Blondie share a partnership together making money off of Tuco's bounty, but when Blondie unties the partnership, Tuco tries to hunt down Blondie. When Blondie and Tuco come across a horse carriage loaded with dead bodies, they soon learn from the only survivor, Bill Carson (Antonio Casale), that he and a few other men have buried a stash of gold in a cemetery. Unfortunately, Carson dies and Tuco only finds out the name of the cemetery, while Blondie finds out the name on the grave. Now the two must keep each other alive in order to find the gold. Angel Eyes (who had been looking for Bill Carson) discovers that Tuco and Blondie met with Carson and knows ...",
    "yt_trailer_code": "OLNktcDs05Y",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/The_Good_The_Bad_and_the_Ugly_1966/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Good_The_Bad_and_the_Ugly_1966/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Good_The_Bad_and_the_Ugly_1966/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Good_The_Bad_and_the_Ugly_1966/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Good_The_Bad_and_the_Ugly_1966/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/10971E23782EFB0AFD17226463BF931A7415428F",
    "hash": "10971E23782EFB0AFD17226463BF931A7415428F",
    "quality": "720p",
    "type": "bluray",
    "seeds": 63,
    "peers": 16,
    "size": "1.20 GB",
    "size_bytes": 1288490189,
    "date_uploaded": "2015-11-01 02:37:53",
    "date_uploaded_unix": 1446341873
    },
    {
    "url": "https://yts.lt/torrent/download/80BC9D85B81180BF0DA309B3F9B899B4DB8B8095",
    "hash": "80BC9D85B81180BF0DA309B3F9B899B4DB8B8095",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 178,
    "peers": 24,
    "size": "2.40 GB",
    "size_bytes": 2576980378,
    "date_uploaded": "2015-11-01 02:37:56",
    "date_uploaded_unix": 1446341876
    }
    ],
    "date_uploaded": "2015-11-01 02:37:53",
    "date_uploaded_unix": 1446341873
    },
    {
    "id": 3488,
    "url": "https://yts.lt/movie/the-lord-of-the-rings-the-fellowship-of-the-ring-2001",
    "imdb_code": "tt0120737",
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "title_english": "The Lord of the Rings: The Fellowship of the Ring",
    "title_long": "The Lord of the Rings: The Fellowship of the Ring (2001)",
    "slug": "the-lord-of-the-rings-the-fellowship-of-the-ring-2001",
    "year": 2001,
    "rating": 8.8,
    "runtime": 178,
    "genres": [
    "Action",
    "Adventure",
    "Drama",
    "Fantasy"
    ],
    "summary": "An ancient Ring thought lost for centuries has been found, and through a strange twist of fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it. However, he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir, and his three Hobbit friends Merry, Pippin, and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign.",
    "description_full": "An ancient Ring thought lost for centuries has been found, and through a strange twist of fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it. However, he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir, and his three Hobbit friends Merry, Pippin, and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign.",
    "synopsis": "An ancient Ring thought lost for centuries has been found, and through a strange twist of fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it. However, he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir, and his three Hobbit friends Merry, Pippin, and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign.",
    "yt_trailer_code": "V75dMMIW2B4",
    "language": "English",
    "mpa_rating": "PG-13",
    "background_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_EXTENDED_2001/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_EXTENDED_2001/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_EXTENDED_2001/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_EXTENDED_2001/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_EXTENDED_2001/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/E175ACD03B68BF0736DFC4B17D1D1496A455E01D",
    "hash": "E175ACD03B68BF0736DFC4B17D1D1496A455E01D",
    "quality": "720p",
    "type": "bluray",
    "seeds": 353,
    "peers": 75,
    "size": "1.41 GB",
    "size_bytes": 1513975972,
    "date_uploaded": "2015-11-01 02:58:08",
    "date_uploaded_unix": 1446343088
    },
    {
    "url": "https://yts.lt/torrent/download/7C286EC055A01E70C4B138FC3901A8995E47B973",
    "hash": "7C286EC055A01E70C4B138FC3901A8995E47B973",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 342,
    "peers": 108,
    "size": "2.40 GB",
    "size_bytes": 2576980378,
    "date_uploaded": "2015-11-01 02:58:12",
    "date_uploaded_unix": 1446343092
    }
    ],
    "date_uploaded": "2015-11-01 02:58:08",
    "date_uploaded_unix": 1446343088
    },
    {
    "id": 7267,
    "url": "https://yts.lt/movie/anand-1971",
    "imdb_code": "tt0066763",
    "title": "Anand",
    "title_english": "Anand",
    "title_long": "Anand (1971)",
    "slug": "anand-1971",
    "year": 1971,
    "rating": 8.8,
    "runtime": 122,
    "genres": [
    "Drama",
    "Musical"
    ],
    "summary": "Dr Bhaskar Bannerjee is not happy with his profession as he cant save the lives of people dying of illness due to poverty.His Dr friend Kulkarni charges huge for imaginary illness of rich and uses that money to people who cant afford treatment.Things change when Anand a cancer patients enters Bhaskar's life Anand is cheerful and believes in spreading happiness to everyone as he knows he is on last stage of cancer and has few months to live.Bhaskar and Anand bond very well Anand also gets Bhaskar's love life back on track and Bhaskar doesn't want him to loose anymore.As time passes Anand's condition starts to deteriorate and everyone around him is just hoping for a miracle.",
    "description_full": "Dr Bhaskar Bannerjee is not happy with his profession as he cant save the lives of people dying of illness due to poverty.His Dr friend Kulkarni charges huge for imaginary illness of rich and uses that money to people who cant afford treatment.Things change when Anand a cancer patients enters Bhaskar's life Anand is cheerful and believes in spreading happiness to everyone as he knows he is on last stage of cancer and has few months to live.Bhaskar and Anand bond very well Anand also gets Bhaskar's love life back on track and Bhaskar doesn't want him to loose anymore.As time passes Anand's condition starts to deteriorate and everyone around him is just hoping for a miracle.",
    "synopsis": "Dr Bhaskar Bannerjee is not happy with his profession as he cant save the lives of people dying of illness due to poverty.His Dr friend Kulkarni charges huge for imaginary illness of rich and uses that money to people who cant afford treatment.Things change when Anand a cancer patients enters Bhaskar's life Anand is cheerful and believes in spreading happiness to everyone as he knows he is on last stage of cancer and has few months to live.Bhaskar and Anand bond very well Anand also gets Bhaskar's love life back on track and Bhaskar doesn't want him to loose anymore.As time passes Anand's condition starts to deteriorate and everyone around him is just hoping for a miracle.",
    "yt_trailer_code": "SSVBSGZeE4Y",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/anand_1971/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/anand_1971/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/anand_1971/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/anand_1971/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/anand_1971/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/6B88C9F3B9640381B7C95329BEB42938B3489279",
    "hash": "6B88C9F3B9640381B7C95329BEB42938B3489279",
    "quality": "720p",
    "type": "bluray",
    "seeds": 6,
    "peers": 2,
    "size": "986.15 MB",
    "size_bytes": 1034053222,
    "date_uploaded": "2018-03-06 06:23:53",
    "date_uploaded_unix": 1520313833
    },
    {
    "url": "https://yts.lt/torrent/download/712358FA136397C725740F2A61488AC827EC4A33",
    "hash": "712358FA136397C725740F2A61488AC827EC4A33",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 12,
    "peers": 3,
    "size": "1.9 GB",
    "size_bytes": 2040109466,
    "date_uploaded": "2018-03-06 08:53:34",
    "date_uploaded_unix": 1520322814
    }
    ],
    "date_uploaded": "2018-03-06 06:23:53",
    "date_uploaded_unix": 1520313833
    },
    {
    "id": 1344,
    "url": "https://yts.lt/movie/goodfellas-1990",
    "imdb_code": "tt0099685",
    "title": "Goodfellas",
    "title_english": "Goodfellas",
    "title_long": "Goodfellas (1990)",
    "slug": "goodfellas-1990",
    "year": 1990,
    "rating": 8.7,
    "runtime": 146,
    "genres": [
    "Action",
    "Biography",
    "Crime",
    "Drama"
    ],
    "summary": "Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?",
    "description_full": "Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?",
    "synopsis": "Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?",
    "yt_trailer_code": "rW2bWAcsPCk",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/Goodfellas_1990/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Goodfellas_1990/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Goodfellas_1990/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Goodfellas_1990/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Goodfellas_1990/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/82A9E0688BAED54D0241DCA945C85B3156C45025",
    "hash": "82A9E0688BAED54D0241DCA945C85B3156C45025",
    "quality": "720p",
    "type": "bluray",
    "seeds": 271,
    "peers": 40,
    "size": "699.03 MB",
    "size_bytes": 732986081,
    "date_uploaded": "2015-10-31 23:43:53",
    "date_uploaded_unix": 1446331433
    },
    {
    "url": "https://yts.lt/torrent/download/B17364CA86A982B54DF38B25B978E1D074605C29",
    "hash": "B17364CA86A982B54DF38B25B978E1D074605C29",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 138,
    "peers": 41,
    "size": "2.32 GB",
    "size_bytes": 2491081032,
    "date_uploaded": "2018-04-25 21:24:22",
    "date_uploaded_unix": 1524684262
    }
    ],
    "date_uploaded": "2015-10-31 23:43:53",
    "date_uploaded_unix": 1446331433
    },
    {
    "id": 2241,
    "url": "https://yts.lt/movie/one-flew-over-the-cuckoos-nest-1975",
    "imdb_code": "tt0073486",
    "title": "One Flew Over the Cuckoo's Nest",
    "title_english": "One Flew Over the Cuckoo's Nest",
    "title_long": "One Flew Over the Cuckoo's Nest (1975)",
    "slug": "one-flew-over-the-cuckoos-nest-1975",
    "year": 1975,
    "rating": 8.7,
    "runtime": 133,
    "genres": [
    "Action",
    "Drama"
    ],
    "summary": "McMurphy has a criminal past and has once again gotten himself into trouble and is sentenced by the court. To escape labor duties in prison, McMurphy pleads insanity and is sent to a ward for the mentally unstable. Once here, McMurphy both endures and stands witness to the abuse and degradation of the oppressive Nurse Ratched, who gains superiority and power through the flaws of the other inmates. McMurphy and the other inmates band together to make a rebellious stance against the atrocious Nurse.",
    "description_full": "McMurphy has a criminal past and has once again gotten himself into trouble and is sentenced by the court. To escape labor duties in prison, McMurphy pleads insanity and is sent to a ward for the mentally unstable. Once here, McMurphy both endures and stands witness to the abuse and degradation of the oppressive Nurse Ratched, who gains superiority and power through the flaws of the other inmates. McMurphy and the other inmates band together to make a rebellious stance against the atrocious Nurse.",
    "synopsis": "McMurphy has a criminal past and has once again gotten himself into trouble and is sentenced by the court. To escape labor duties in prison, McMurphy pleads insanity and is sent to a ward for the mentally unstable. Once here, McMurphy both endures and stands witness to the abuse and degradation of the oppressive Nurse Ratched, who gains superiority and power through the flaws of the other inmates. McMurphy and the other inmates band together to make a rebellious stance against the atrocious Nurse.",
    "yt_trailer_code": "6aJT5fGCRPk",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/One_Flew_Over_the_Cuckoos_Nest_1975/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/One_Flew_Over_the_Cuckoos_Nest_1975/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/One_Flew_Over_the_Cuckoos_Nest_1975/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/One_Flew_Over_the_Cuckoos_Nest_1975/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/One_Flew_Over_the_Cuckoos_Nest_1975/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/B81DF3E2AADDAC24AF86800C55D78F2D02DEC008",
    "hash": "B81DF3E2AADDAC24AF86800C55D78F2D02DEC008",
    "quality": "720p",
    "type": "bluray",
    "seeds": 53,
    "peers": 13,
    "size": "900.38 MB",
    "size_bytes": 944116859,
    "date_uploaded": "2015-11-01 01:30:32",
    "date_uploaded_unix": 1446337832
    },
    {
    "url": "https://yts.lt/torrent/download/BFF25FBBAC88B6B9D24DBC18B359734015C8ABF4",
    "hash": "BFF25FBBAC88B6B9D24DBC18B359734015C8ABF4",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 163,
    "peers": 27,
    "size": "1.80 GB",
    "size_bytes": 1932735283,
    "date_uploaded": "2015-11-01 01:30:34",
    "date_uploaded_unix": 1446337834
    }
    ],
    "date_uploaded": "2015-11-01 01:30:32",
    "date_uploaded_unix": 1446337832
    }
    ]
    },
    "@meta": {
    "server_time": 1573564472,
    "server_timezone": "CET",
    "api_version": 2,
    "execution_time": "0 ms"
    }
    }