export const page2 = {
    "status": "ok",
    "status_message": "Query was successful",
    "data": {
    "movie_count": 13813,
    "limit": 20,
    "page_number": 2,
    "movies": [
    {
    "id": 2862,
    "url": "https://yts.lt/movie/star-wars-episode-v-the-empire-strikes-back-1980",
    "imdb_code": "tt0080684",
    "title": "Star Wars: Episode V - The Empire Strikes Back",
    "title_english": "Star Wars: Episode V - The Empire Strikes Back",
    "title_long": "Star Wars: Episode V - The Empire Strikes Back (1980)",
    "slug": "star-wars-episode-v-the-empire-strikes-back-1980",
    "year": 1980,
    "rating": 8.7,
    "runtime": 124,
    "genres": [
    "Action",
    "Adventure",
    "Fantasy",
    "Sci-Fi"
    ],
    "summary": "Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi Master's help will Luke survive when the Dark Side of the Force beckons him into the ultimate duel with Darth Vader.",
    "description_full": "Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi Master's help will Luke survive when the Dark Side of the Force beckons him into the ultimate duel with Darth Vader.",
    "synopsis": "Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi Master's help will Luke survive when the Dark Side of the Force beckons him into the ultimate duel with Darth Vader.",
    "yt_trailer_code": "KwYa7UpoWtM",
    "language": "English",
    "mpa_rating": "PG",
    "background_image": "https://yts.lt/assets/images/movies/Star_Wars_Episode_V_The_Empire_Strikes_Back_1980/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Star_Wars_Episode_V_The_Empire_Strikes_Back_1980/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Star_Wars_Episode_V_The_Empire_Strikes_Back_1980/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Star_Wars_Episode_V_The_Empire_Strikes_Back_1980/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Star_Wars_Episode_V_The_Empire_Strikes_Back_1980/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/0E5519DBB0678BC824CE863CB2F4DDD37D0C1C9A",
    "hash": "0E5519DBB0678BC824CE863CB2F4DDD37D0C1C9A",
    "quality": "720p",
    "type": "bluray",
    "seeds": 70,
    "peers": 24,
    "size": "1.08 GB",
    "size_bytes": 1159641170,
    "date_uploaded": "2018-04-26 04:24:10",
    "date_uploaded_unix": 1524709450
    },
    {
    "url": "https://yts.lt/torrent/download/898880149B304FEAA5FF6F6DE633AA4C5703DC1A",
    "hash": "898880149B304FEAA5FF6F6DE633AA4C5703DC1A",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 410,
    "peers": 84,
    "size": "1.70 GB",
    "size_bytes": 1825361101,
    "date_uploaded": "2015-11-01 01:41:42",
    "date_uploaded_unix": 1446338502
    }
    ],
    "date_uploaded": "2018-04-26 04:24:10",
    "date_uploaded_unix": 1524709450
    },
    {
    "id": 6532,
    "url": "https://yts.lt/movie/queen-rock-montreal-live-aid-2007",
    "imdb_code": "tt1421377",
    "title": "Queen Rock Montreal & Live Aid",
    "title_english": "Queen Rock Montreal & Live Aid",
    "title_long": "Queen Rock Montreal & Live Aid (2007)",
    "slug": "queen-rock-montreal-live-aid-2007",
    "year": 2007,
    "rating": 8.7,
    "runtime": 138,
    "genres": [
    "Action",
    "Documentary",
    "Music"
    ],
    "summary": "The movie contains two concerts of the British rock band Queen. The first concert is their show at Montreal in November 1981. The second concert is their live performance at Live Aid in 1985.",
    "description_full": "The movie contains two concerts of the British rock band Queen. The first concert is their show at Montreal in November 1981. The second concert is their live performance at Live Aid in 1985.",
    "synopsis": "The movie contains two concerts of the British rock band Queen. The first concert is their show at Montreal in November 1981. The second concert is their live performance at Live Aid in 1985.",
    "yt_trailer_code": "A22oy8dFjqc",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/queen_rock_montreal_live_aid_2007/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/queen_rock_montreal_live_aid_2007/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/queen_rock_montreal_live_aid_2007/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/queen_rock_montreal_live_aid_2007/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/queen_rock_montreal_live_aid_2007/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/4D0860BE6A70BEA795F14FFE5E60068302FCA625",
    "hash": "4D0860BE6A70BEA795F14FFE5E60068302FCA625",
    "quality": "720p",
    "type": "bluray",
    "seeds": 16,
    "peers": 1,
    "size": "712.59 MB",
    "size_bytes": 747204772,
    "date_uploaded": "2017-05-30 04:24:38",
    "date_uploaded_unix": 1496111078
    },
    {
    "url": "https://yts.lt/torrent/download/829150F8EBA980DD000CED1F9004AA793B033D66",
    "hash": "829150F8EBA980DD000CED1F9004AA793B033D66",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 24,
    "peers": 8,
    "size": "1.46 GB",
    "size_bytes": 1567663063,
    "date_uploaded": "2017-05-30 08:27:22",
    "date_uploaded_unix": 1496125642
    }
    ],
    "date_uploaded": "2017-05-30 04:24:38",
    "date_uploaded_unix": 1496111078
    },
    {
    "id": 3490,
    "url": "https://yts.lt/movie/the-lord-of-the-rings-the-two-towers-2002",
    "imdb_code": "tt0167261",
    "title": "The Lord of the Rings: The Two Towers",
    "title_english": "The Lord of the Rings: The Two Towers",
    "title_long": "The Lord of the Rings: The Two Towers (2002)",
    "slug": "the-lord-of-the-rings-the-two-towers-2002",
    "year": 2002,
    "rating": 8.7,
    "runtime": 179,
    "genres": [
    "Action",
    "Adventure",
    "Drama",
    "Family",
    "Fantasy"
    ],
    "summary": "The continuing quest of Frodo and the Fellowship to destroy the One Ring. Frodo and Sam discover they are being followed by the mysterious Gollum. Aragorn, the Elf archer Legolas, and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman's deadly spell.",
    "description_full": "The continuing quest of Frodo and the Fellowship to destroy the One Ring. Frodo and Sam discover they are being followed by the mysterious Gollum. Aragorn, the Elf archer Legolas, and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman's deadly spell.",
    "synopsis": "The continuing quest of Frodo and the Fellowship to destroy the One Ring. Frodo and Sam discover they are being followed by the mysterious Gollum. Aragorn, the Elf archer Legolas, and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman's deadly spell.",
    "yt_trailer_code": "cvCktPUwkW0",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Two_Towers_EXTENDED_2002/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Two_Towers_EXTENDED_2002/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Two_Towers_EXTENDED_2002/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Two_Towers_EXTENDED_2002/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Lord_of_the_Rings_The_Two_Towers_EXTENDED_2002/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/2186007B26ACE9270FD6C9658213D081C698DC22",
    "hash": "2186007B26ACE9270FD6C9658213D081C698DC22",
    "quality": "720p",
    "type": "bluray",
    "seeds": 197,
    "peers": 59,
    "size": "1.50 GB",
    "size_bytes": 1610612736,
    "date_uploaded": "2015-11-01 02:58:24",
    "date_uploaded_unix": 1446343104
    },
    {
    "url": "https://yts.lt/torrent/download/EBDA5B39978F58B50B2666A808A11C971A9CF080",
    "hash": "EBDA5B39978F58B50B2666A808A11C971A9CF080",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 346,
    "peers": 98,
    "size": "3.00 GB",
    "size_bytes": 3221225472,
    "date_uploaded": "2015-11-01 02:58:27",
    "date_uploaded_unix": 1446343107
    }
    ],
    "date_uploaded": "2015-11-01 02:58:24",
    "date_uploaded_unix": 1446343104
    },
    {
    "id": 3525,
    "url": "https://yts.lt/movie/the-matrix-1999",
    "imdb_code": "tt0133093",
    "title": "The Matrix",
    "title_english": "The Matrix",
    "title_long": "The Matrix (1999)",
    "slug": "the-matrix-1999",
    "year": 1999,
    "rating": 8.7,
    "runtime": 136,
    "genres": [
    "Action",
    "Sci-Fi"
    ],
    "summary": "Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the humans' body heat and electrochemical energy and who imprison their minds within an artificial reality known as the Matrix. As a rebel against the machines, Neo must return to the Matrix and confront the agents: super-powerful computer programs devoted to snuffing out Neo and the entire human rebellion.",
    "description_full": "Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the humans' body heat and electrochemical energy and who imprison their minds within an artificial reality known as the Matrix. As a rebel against the machines, Neo must return to the Matrix and confront the agents: super-powerful computer programs devoted to snuffing out Neo and the entire human rebellion.",
    "synopsis": "Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the humans' body heat and electrochemical energy and who imprison their minds within an artificial reality known as the Matrix. As a rebel against the machines, Neo must return to the Matrix and confront the agents: super-powerful computer programs devoted to snuffing out Neo and the entire human rebellion.",
    "yt_trailer_code": "m8e-FF8MsqU",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/The_Matrix_1999/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Matrix_1999/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Matrix_1999/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Matrix_1999/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Matrix_1999/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/363BC6C534B1430C6758318D196CCD61DB61B647",
    "hash": "363BC6C534B1430C6758318D196CCD61DB61B647",
    "quality": "720p",
    "type": "bluray",
    "seeds": 328,
    "peers": 60,
    "size": "703.69 MB",
    "size_bytes": 737872445,
    "date_uploaded": "2015-11-01 03:02:16",
    "date_uploaded_unix": 1446343336
    },
    {
    "url": "https://yts.lt/torrent/download/D7A46713EAEE18C746B3254B7D1492A50FD9D6CE",
    "hash": "D7A46713EAEE18C746B3254B7D1492A50FD9D6CE",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 336,
    "peers": 99,
    "size": "1.86 GB",
    "size_bytes": 1997159793,
    "date_uploaded": "2015-11-01 03:02:18",
    "date_uploaded_unix": 1446343338
    }
    ],
    "date_uploaded": "2015-11-01 03:02:16",
    "date_uploaded_unix": 1446343336
    },
    {
    "id": 7850,
    "url": "https://yts.lt/movie/be-here-now-2015",
    "imdb_code": "tt2473476",
    "title": "Be Here Now",
    "title_english": "Be Here Now",
    "title_long": "Be Here Now (2015)",
    "slug": "be-here-now-2015",
    "year": 2015,
    "rating": 8.7,
    "runtime": 100,
    "genres": [
    "Action",
    "Biography",
    "Documentary",
    "Drama",
    "Family"
    ],
    "summary": "As though life is imitating art, actor and sex-symbol, Andy Whitfield, had just become a star as the lead in the hit television series,'Spartacus,' when he is faced with his biggest personal challenge - life-threatening cancer. 'Be Here Now' is a feature documentary that follows him on his dramatic journey to cure himself. Confirmed in matching affirmative tattoos, he and his charismatic wife and their two children, commit to taking Andy's healing into their own hands and living life fully, not in the shadows of the disease. Each step tests their limits and strength of character, while revealing their tenderness, humor and determination. And, as each person goes through their own transformations, the film becomes an inspiring and universal story of courage, love and resilience.",
    "description_full": "As though life is imitating art, actor and sex-symbol, Andy Whitfield, had just become a star as the lead in the hit television series,'Spartacus,' when he is faced with his biggest personal challenge - life-threatening cancer. 'Be Here Now' is a feature documentary that follows him on his dramatic journey to cure himself. Confirmed in matching affirmative tattoos, he and his charismatic wife and their two children, commit to taking Andy's healing into their own hands and living life fully, not in the shadows of the disease. Each step tests their limits and strength of character, while revealing their tenderness, humor and determination. And, as each person goes through their own transformations, the film becomes an inspiring and universal story of courage, love and resilience.",
    "synopsis": "As though life is imitating art, actor and sex-symbol, Andy Whitfield, had just become a star as the lead in the hit television series,'Spartacus,' when he is faced with his biggest personal challenge - life-threatening cancer. 'Be Here Now' is a feature documentary that follows him on his dramatic journey to cure himself. Confirmed in matching affirmative tattoos, he and his charismatic wife and their two children, commit to taking Andy's healing into their own hands and living life fully, not in the shadows of the disease. Each step tests their limits and strength of character, while revealing their tenderness, humor and determination. And, as each person goes through their own transformations, the film becomes an inspiring and universal story of courage, love and resilience.",
    "yt_trailer_code": "uLxoDqVG3bE",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/be_here_now_2015/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/be_here_now_2015/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/be_here_now_2015/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/be_here_now_2015/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/be_here_now_2015/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/4BB2849478CDEEDDB3A8DEF999C252111B4D1606",
    "hash": "4BB2849478CDEEDDB3A8DEF999C252111B4D1606",
    "quality": "720p",
    "type": "web",
    "seeds": 20,
    "peers": 5,
    "size": "925.7 MB",
    "size_bytes": 970666803,
    "date_uploaded": "2018-05-22 03:51:45",
    "date_uploaded_unix": 1526953905
    },
    {
    "url": "https://yts.lt/torrent/download/7E904AA2F3070C5379E39B5348BC519CB2DF942E",
    "hash": "7E904AA2F3070C5379E39B5348BC519CB2DF942E",
    "quality": "1080p",
    "type": "web",
    "seeds": 16,
    "peers": 7,
    "size": "1.75 GB",
    "size_bytes": 1879048192,
    "date_uploaded": "2018-05-22 06:19:48",
    "date_uploaded_unix": 1526962788
    }
    ],
    "date_uploaded": "2018-05-22 03:51:45",
    "date_uploaded_unix": 1526953905
    },
    {
    "id": 8131,
    "url": "https://yts.lt/movie/human-2015",
    "imdb_code": "tt3327994",
    "title": "Human",
    "title_english": "Human",
    "title_long": "Human (2015)",
    "slug": "human-2015",
    "year": 2015,
    "rating": 8.7,
    "runtime": 190,
    "genres": [
    "Documentary"
    ],
    "summary": "A collection of stories about and images of our world, offering an immersion to the core of what it means to be human.",
    "description_full": "A collection of stories about and images of our world, offering an immersion to the core of what it means to be human.",
    "synopsis": "A collection of stories about and images of our world, offering an immersion to the core of what it means to be human.",
    "yt_trailer_code": "0-Retnj3TsA",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/human_2015/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/human_2015/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/human_2015/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/human_2015/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/human_2015/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/5F619B4A5D3196A91DE2535B54F5C529842683B7",
    "hash": "5F619B4A5D3196A91DE2535B54F5C529842683B7",
    "quality": "720p",
    "type": "bluray",
    "seeds": 19,
    "peers": 5,
    "size": "1.24 GB",
    "size_bytes": 1331439862,
    "date_uploaded": "2018-06-27 05:44:36",
    "date_uploaded_unix": 1530071076
    },
    {
    "url": "https://yts.lt/torrent/download/C4B9EB0790FC64E650E002D20D1131E002EA859A",
    "hash": "C4B9EB0790FC64E650E002D20D1131E002EA859A",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 22,
    "peers": 4,
    "size": "2.39 GB",
    "size_bytes": 2566242959,
    "date_uploaded": "2018-06-27 08:41:39",
    "date_uploaded_unix": 1530081699
    }
    ],
    "date_uploaded": "2018-06-27 05:44:36",
    "date_uploaded_unix": 1530071076
    },
    {
    "id": 1632,
    "url": "https://yts.lt/movie/interstellar-2014",
    "imdb_code": "tt0816692",
    "title": "Interstellar",
    "title_english": "Interstellar",
    "title_long": "Interstellar (2014)",
    "slug": "interstellar-2014",
    "year": 2014,
    "rating": 8.6,
    "runtime": 169,
    "genres": [
    "Action",
    "Adventure",
    "Drama",
    "Sci-Fi"
    ],
    "summary": "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.",
    "description_full": "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.",
    "synopsis": "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.",
    "yt_trailer_code": "2LqzF5WauAw",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/interstellar_2014/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/interstellar_2014/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/interstellar_2014/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/interstellar_2014/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/interstellar_2014/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/6E88B3F25BA49D483D740A652BF013C341BC5373",
    "hash": "6E88B3F25BA49D483D740A652BF013C341BC5373",
    "quality": "720p",
    "type": "bluray",
    "seeds": 389,
    "peers": 50,
    "size": "1.02 GB",
    "size_bytes": 1095216660,
    "date_uploaded": "2015-11-01 00:18:06",
    "date_uploaded_unix": 1446333486
    },
    {
    "url": "https://yts.lt/torrent/download/89599BF4DC369A3A8ECA26411C5CCF922D78B486",
    "hash": "89599BF4DC369A3A8ECA26411C5CCF922D78B486",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 934,
    "peers": 153,
    "size": "2.26 GB",
    "size_bytes": 2426656522,
    "date_uploaded": "2015-11-01 00:18:07",
    "date_uploaded_unix": 1446333487
    }
    ],
    "date_uploaded": "2015-11-01 00:18:06",
    "date_uploaded_unix": 1446333486
    },
    {
    "id": 1659,
    "url": "https://yts.lt/movie/its-a-wonderful-life-1946",
    "imdb_code": "tt0038650",
    "title": "It's a Wonderful Life",
    "title_english": "It's a Wonderful Life",
    "title_long": "It's a Wonderful Life (1946)",
    "slug": "its-a-wonderful-life-1946",
    "year": 1946,
    "rating": 8.6,
    "runtime": 130,
    "genres": [
    "Action",
    "Drama",
    "Family",
    "Fantasy",
    "Romance"
    ],
    "summary": "George Bailey has spent his entire life giving of himself to the people of Bedford Falls. He has always longed to travel but never had the opportunity in order to prevent rich skinflint Mr. Potter from taking over the entire town. All that prevents him from doing so is George's modest building and loan company, which was founded by his generous father. But on Christmas Eve, George's Uncle Billy loses the business's $8,000 while intending to deposit it in the bank. Potter finds the misplaced money and hides it from Billy. When the bank examiner discovers the shortage later that night, George realizes that he will be held responsible and sent to jail and the company will collapse, finally allowing Potter to take over the town. Thinking of his wife, their young children, and others he loves will be better off with him dead, he contemplates suicide. But the prayers of his loved ones result in a gentle angel named Clarence coming to earth to help George, with the promise of earning his ...",
    "description_full": "George Bailey has spent his entire life giving of himself to the people of Bedford Falls. He has always longed to travel but never had the opportunity in order to prevent rich skinflint Mr. Potter from taking over the entire town. All that prevents him from doing so is George's modest building and loan company, which was founded by his generous father. But on Christmas Eve, George's Uncle Billy loses the business's $8,000 while intending to deposit it in the bank. Potter finds the misplaced money and hides it from Billy. When the bank examiner discovers the shortage later that night, George realizes that he will be held responsible and sent to jail and the company will collapse, finally allowing Potter to take over the town. Thinking of his wife, their young children, and others he loves will be better off with him dead, he contemplates suicide. But the prayers of his loved ones result in a gentle angel named Clarence coming to earth to help George, with the promise of earning his ...",
    "synopsis": "George Bailey has spent his entire life giving of himself to the people of Bedford Falls. He has always longed to travel but never had the opportunity in order to prevent rich skinflint Mr. Potter from taking over the entire town. All that prevents him from doing so is George's modest building and loan company, which was founded by his generous father. But on Christmas Eve, George's Uncle Billy loses the business's $8,000 while intending to deposit it in the bank. Potter finds the misplaced money and hides it from Billy. When the bank examiner discovers the shortage later that night, George realizes that he will be held responsible and sent to jail and the company will collapse, finally allowing Potter to take over the town. Thinking of his wife, their young children, and others he loves will be better off with him dead, he contemplates suicide. But the prayers of his loved ones result in a gentle angel named Clarence coming to earth to help George, with the promise of earning his ...",
    "yt_trailer_code": "uhq9Ke8M25M",
    "language": "English",
    "mpa_rating": "PG",
    "background_image": "https://yts.lt/assets/images/movies/Its_a_Wonderful_Life_1946/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Its_a_Wonderful_Life_1946/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Its_a_Wonderful_Life_1946/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Its_a_Wonderful_Life_1946/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Its_a_Wonderful_Life_1946/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/D325FF1239775941019469E835883247C365F324",
    "hash": "D325FF1239775941019469E835883247C365F324",
    "quality": "720p",
    "type": "bluray",
    "seeds": 75,
    "peers": 6,
    "size": "699.64 MB",
    "size_bytes": 733625713,
    "date_uploaded": "2015-11-01 00:21:04",
    "date_uploaded_unix": 1446333664
    },
    {
    "url": "https://yts.lt/torrent/download/FCFD50DD87830C8DEB530A4131BDED170E162160",
    "hash": "FCFD50DD87830C8DEB530A4131BDED170E162160",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 45,
    "peers": 9,
    "size": "2.05 GB",
    "size_bytes": 2201170739,
    "date_uploaded": "2018-04-25 23:56:54",
    "date_uploaded_unix": 1524693414
    }
    ],
    "date_uploaded": "2015-11-01 00:21:04",
    "date_uploaded_unix": 1446333664
    },
    {
    "id": 7662,
    "url": "https://yts.lt/movie/life-is-beautiful-1997",
    "imdb_code": "tt0118799",
    "title": "Life Is Beautiful",
    "title_english": "Life Is Beautiful",
    "title_long": "Life Is Beautiful (1997)",
    "slug": "life-is-beautiful-1997",
    "year": 1997,
    "rating": 8.6,
    "runtime": 116,
    "genres": [
    "Comedy",
    "Drama",
    "Romance",
    "War"
    ],
    "summary": "In 1930s Italy, a carefree Jewish book keeper named Guido starts a fairy tale life by courting and marrying a lovely woman from a nearby city. Guido and his wife have a son and live happily together until the occupation of Italy by German forces. In an attempt to hold his family together and help his son survive the horrors of a Jewish Concentration Camp, Guido imagines that the Holocaust is a game and that the grand prize for winning is a tank.",
    "description_full": "In 1930s Italy, a carefree Jewish book keeper named Guido starts a fairy tale life by courting and marrying a lovely woman from a nearby city. Guido and his wife have a son and live happily together until the occupation of Italy by German forces. In an attempt to hold his family together and help his son survive the horrors of a Jewish Concentration Camp, Guido imagines that the Holocaust is a game and that the grand prize for winning is a tank.",
    "synopsis": "In 1930s Italy, a carefree Jewish book keeper named Guido starts a fairy tale life by courting and marrying a lovely woman from a nearby city. Guido and his wife have a son and live happily together until the occupation of Italy by German forces. In an attempt to hold his family together and help his son survive the horrors of a Jewish Concentration Camp, Guido imagines that the Holocaust is a game and that the grand prize for winning is a tank.",
    "yt_trailer_code": "pAYEQP8gx3w",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/life_is_beautiful_1997/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/life_is_beautiful_1997/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/life_is_beautiful_1997/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/life_is_beautiful_1997/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/life_is_beautiful_1997/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/82F1C75F14B96EBF7D231538F29EDF92D8B3C79C",
    "hash": "82F1C75F14B96EBF7D231538F29EDF92D8B3C79C",
    "quality": "720p",
    "type": "bluray",
    "seeds": 61,
    "peers": 14,
    "size": "989.83 MB",
    "size_bytes": 1037911982,
    "date_uploaded": "2018-04-26 01:16:56",
    "date_uploaded_unix": 1524698216
    },
    {
    "url": "https://yts.lt/torrent/download/35E38EB6225EA407A6DA679A59FEC79ECCC8B941",
    "hash": "35E38EB6225EA407A6DA679A59FEC79ECCC8B941",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 100,
    "peers": 16,
    "size": "1.86 GB",
    "size_bytes": 1997159793,
    "date_uploaded": "2018-04-26 03:48:25",
    "date_uploaded_unix": 1524707305
    }
    ],
    "date_uploaded": "2018-04-26 01:16:56",
    "date_uploaded_unix": 1524698216
    },
    {
    "id": 2626,
    "url": "https://yts.lt/movie/saving-private-ryan-1998",
    "imdb_code": "tt0120815",
    "title": "Saving Private Ryan",
    "title_english": "Saving Private Ryan",
    "title_long": "Saving Private Ryan (1998)",
    "slug": "saving-private-ryan-1998",
    "year": 1998,
    "rating": 8.6,
    "runtime": 169,
    "genres": [
    "Action",
    "Drama",
    "War"
    ],
    "summary": "Opening with the Allied invasion of Normandy on 6 June 1944, members of the 2nd Ranger Battalion under Cpt. Miller fight ashore to secure a beachhead. Amidst the fighting, two brothers are killed in action. Earlier in New Guinea, a third brother is KIA. Their mother, Mrs. Ryan, is to receive all three of the grave telegrams on the same day. The United States Army Chief of Staff, George C. Marshall, is given an opportunity to alleviate some of her grief when he learns of a fourth brother, Private James Ryan, and decides to send out 8 men (Cpt. Miller and select members from 2nd Rangers) to find him and bring him back home to his mother...",
    "description_full": "Opening with the Allied invasion of Normandy on 6 June 1944, members of the 2nd Ranger Battalion under Cpt. Miller fight ashore to secure a beachhead. Amidst the fighting, two brothers are killed in action. Earlier in New Guinea, a third brother is KIA. Their mother, Mrs. Ryan, is to receive all three of the grave telegrams on the same day. The United States Army Chief of Staff, George C. Marshall, is given an opportunity to alleviate some of her grief when he learns of a fourth brother, Private James Ryan, and decides to send out 8 men (Cpt. Miller and select members from 2nd Rangers) to find him and bring him back home to his mother...",
    "synopsis": "Opening with the Allied invasion of Normandy on 6 June 1944, members of the 2nd Ranger Battalion under Cpt. Miller fight ashore to secure a beachhead. Amidst the fighting, two brothers are killed in action. Earlier in New Guinea, a third brother is KIA. Their mother, Mrs. Ryan, is to receive all three of the grave telegrams on the same day. The United States Army Chief of Staff, George C. Marshall, is given an opportunity to alleviate some of her grief when he learns of a fourth brother, Private James Ryan, and decides to send out 8 men (Cpt. Miller and select members from 2nd Rangers) to find him and bring him back home to his mother...",
    "yt_trailer_code": "RYExstiQlLc",
    "language": "English",
    "mpa_rating": "R",
    "background_image": "https://yts.lt/assets/images/movies/Saving_Private_Ryan_1998/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Saving_Private_Ryan_1998/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Saving_Private_Ryan_1998/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Saving_Private_Ryan_1998/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Saving_Private_Ryan_1998/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/71DFC2B9B93B984520FF5FA66F2FAF9F48DD174D",
    "hash": "71DFC2B9B93B984520FF5FA66F2FAF9F48DD174D",
    "quality": "720p",
    "type": "bluray",
    "seeds": 171,
    "peers": 51,
    "size": "978.44 MB",
    "size_bytes": 1025968701,
    "date_uploaded": "2015-11-01 01:14:38",
    "date_uploaded_unix": 1446336878
    },
    {
    "url": "https://yts.lt/torrent/download/67D62505CB3C11C1506C3378FFC64DFA438EA8BA",
    "hash": "67D62505CB3C11C1506C3378FFC64DFA438EA8BA",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 286,
    "peers": 78,
    "size": "2.20 GB",
    "size_bytes": 2362232013,
    "date_uploaded": "2015-11-01 01:14:39",
    "date_uploaded_unix": 1446336879
    }
    ],
    "date_uploaded": "2015-11-01 01:14:38",
    "date_uploaded_unix": 1446336878
    },
    {
    "id": 2652,
    "url": "https://yts.lt/movie/se7en-1995",
    "imdb_code": "tt0114369",
    "title": "Se7en",
    "title_english": "Se7en",
    "title_long": "Se7en (1995)",
    "slug": "se7en-1995",
    "year": 1995,
    "rating": 8.6,
    "runtime": 127,
    "genres": [
    "Action",
    "Crime",
    "Drama",
    "Mystery",
    "Thriller"
    ],
    "summary": "A film about two homicide detectives' (Morgan Freeman and Brad Pitt) desperate hunt for a serial killer who justifies his crimes as absolution for the world's ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic \"John Doe\" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer's terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer's modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer...",
    "description_full": "A film about two homicide detectives' (Morgan Freeman and Brad Pitt) desperate hunt for a serial killer who justifies his crimes as absolution for the world's ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic \"John Doe\" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer's terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer's modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer...",
    "synopsis": "A film about two homicide detectives' (Morgan Freeman and Brad Pitt) desperate hunt for a serial killer who justifies his crimes as absolution for the world's ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic \"John Doe\" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer's terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer's modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer...",
    "yt_trailer_code": "SpKbZ_3zlb0",
    "language": "English",
    "mpa_rating": "R",
    "background_image": "https://yts.lt/assets/images/movies/Se7en_1995/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Se7en_1995/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Se7en_1995/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Se7en_1995/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Se7en_1995/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/3D1ADE5E738AEE2ACA577B9D922B0E2903159BE7",
    "hash": "3D1ADE5E738AEE2ACA577B9D922B0E2903159BE7",
    "quality": "720p",
    "type": "bluray",
    "seeds": 140,
    "peers": 33,
    "size": "695.78 MB",
    "size_bytes": 729578209,
    "date_uploaded": "2015-11-01 01:17:32",
    "date_uploaded_unix": 1446337052
    },
    {
    "url": "https://yts.lt/torrent/download/C62DB96F2940FFFC47A76C82C88857A68E27A235",
    "hash": "C62DB96F2940FFFC47A76C82C88857A68E27A235",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 165,
    "peers": 44,
    "size": "1022.94 MB",
    "size_bytes": 1072630333,
    "date_uploaded": "2015-11-01 01:17:35",
    "date_uploaded_unix": 1446337055
    }
    ],
    "date_uploaded": "2015-11-01 01:17:32",
    "date_uploaded_unix": 1446337052
    },
    {
    "id": 2858,
    "url": "https://yts.lt/movie/star-wars-episode-iv-a-new-hope-1977",
    "imdb_code": "tt0076759",
    "title": "Star Wars: Episode IV - A New Hope",
    "title_english": "Star Wars: Episode IV - A New Hope",
    "title_long": "Star Wars: Episode IV - A New Hope (1977)",
    "slug": "star-wars-episode-iv-a-new-hope-1977",
    "year": 1977,
    "rating": 8.6,
    "runtime": 121,
    "genres": [
    "Action",
    "Adventure",
    "Fantasy",
    "Sci-Fi"
    ],
    "summary": "The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.",
    "description_full": "The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.",
    "synopsis": "The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.",
    "yt_trailer_code": "vZ734NWnAHA",
    "language": "English",
    "mpa_rating": "PG",
    "background_image": "https://yts.lt/assets/images/movies/Star_Wars_Episode_IV_A_New_Hope_1977/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/Star_Wars_Episode_IV_A_New_Hope_1977/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/Star_Wars_Episode_IV_A_New_Hope_1977/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/Star_Wars_Episode_IV_A_New_Hope_1977/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/Star_Wars_Episode_IV_A_New_Hope_1977/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/8AD627B1DD1FFA6B46E977796A42D34DDF3A0DDE",
    "hash": "8AD627B1DD1FFA6B46E977796A42D34DDF3A0DDE",
    "quality": "720p",
    "type": "bluray",
    "seeds": 98,
    "peers": 15,
    "size": "913.96 MB",
    "size_bytes": 958356521,
    "date_uploaded": "2017-10-27 10:33:32",
    "date_uploaded_unix": 1509093212
    },
    {
    "url": "https://yts.lt/torrent/download/FE1E1069DE410FB44157F02B4F6655DDE99621C6",
    "hash": "FE1E1069DE410FB44157F02B4F6655DDE99621C6",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 322,
    "peers": 84,
    "size": "1.70 GB",
    "size_bytes": 1825361101,
    "date_uploaded": "2015-11-01 01:41:24",
    "date_uploaded_unix": 1446338484
    }
    ],
    "date_uploaded": "2017-10-27 10:33:32",
    "date_uploaded_unix": 1509093212
    },
    {
    "id": 3326,
    "url": "https://yts.lt/movie/the-green-mile-1999",
    "imdb_code": "tt0120689",
    "title": "The Green Mile",
    "title_english": "The Green Mile",
    "title_long": "The Green Mile (1999)",
    "slug": "the-green-mile-1999",
    "year": 1999,
    "rating": 8.6,
    "runtime": 189,
    "genres": [
    "Action",
    "Crime",
    "Drama",
    "Fantasy",
    "Mystery"
    ],
    "summary": "Death Row guards at a penitentiary, in the 1930's, have a moral dilemma with their job when they discover one of their prisoners, a convicted murderer, has a special gift.",
    "description_full": "Death Row guards at a penitentiary, in the 1930's, have a moral dilemma with their job when they discover one of their prisoners, a convicted murderer, has a special gift.",
    "synopsis": "Death Row guards at a penitentiary, in the 1930's, have a moral dilemma with their job when they discover one of their prisoners, a convicted murderer, has a special gift.",
    "yt_trailer_code": "ctRK-4Vt7dA",
    "language": "English",
    "mpa_rating": "R",
    "background_image": "https://yts.lt/assets/images/movies/The_Green_Mile_1999/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Green_Mile_1999/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Green_Mile_1999/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Green_Mile_1999/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Green_Mile_1999/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/194138CADFB197F9BBB8253EB07372F125D41072",
    "hash": "194138CADFB197F9BBB8253EB07372F125D41072",
    "quality": "720p",
    "type": "bluray",
    "seeds": 213,
    "peers": 40,
    "size": "1.25 GB",
    "size_bytes": 1342177280,
    "date_uploaded": "2015-11-01 02:39:13",
    "date_uploaded_unix": 1446341953
    },
    {
    "url": "https://yts.lt/torrent/download/58C5933784BE4ABC8C357E670E2251B1FA562B56",
    "hash": "58C5933784BE4ABC8C357E670E2251B1FA562B56",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 163,
    "peers": 37,
    "size": "2.50 GB",
    "size_bytes": 2684354560,
    "date_uploaded": "2015-11-01 02:39:16",
    "date_uploaded_unix": 1446341956
    }
    ],
    "date_uploaded": "2015-11-01 02:39:13",
    "date_uploaded_unix": 1446341953
    },
    {
    "id": 3714,
    "url": "https://yts.lt/movie/the-silence-of-the-lambs-1991",
    "imdb_code": "tt0102926",
    "title": "The Silence of the Lambs",
    "title_english": "The Silence of the Lambs",
    "title_long": "The Silence of the Lambs (1991)",
    "slug": "the-silence-of-the-lambs-1991",
    "year": 1991,
    "rating": 8.6,
    "runtime": 118,
    "genres": [
    "Action",
    "Crime",
    "Drama",
    "Horror",
    "Mystery",
    "Thriller"
    ],
    "summary": "F.B.I. trainee Clarice Starling (Jodie Foster) works hard to advance her career, while trying to hide or put behind her West Virginia roots, of which if some knew, would automatically classify her as being backward or white trash. After graduation, she aspires to work in the agency's Behavioral Science Unit under the leadership of Jack Crawford (Scott Glenn). While she is still a trainee, Crawford asks her to question Dr. Hannibal Lecter (Sir Anthony Hopkins), a psychiatrist imprisoned, thus far, for eight years in maximum security isolation for being a serial killer who cannibalized his victims. Clarice is able to figure out the assignment is to pick Lecter's brains to help them solve another serial murder case, that of someone coined by the media as \"Buffalo Bill\" (Ted Levine), who has so far killed five victims, all located in the eastern U.S., all young women, who are slightly overweight (especially around the hips), all who were drowned in natural bodies of water, and all who ...",
    "description_full": "F.B.I. trainee Clarice Starling (Jodie Foster) works hard to advance her career, while trying to hide or put behind her West Virginia roots, of which if some knew, would automatically classify her as being backward or white trash. After graduation, she aspires to work in the agency's Behavioral Science Unit under the leadership of Jack Crawford (Scott Glenn). While she is still a trainee, Crawford asks her to question Dr. Hannibal Lecter (Sir Anthony Hopkins), a psychiatrist imprisoned, thus far, for eight years in maximum security isolation for being a serial killer who cannibalized his victims. Clarice is able to figure out the assignment is to pick Lecter's brains to help them solve another serial murder case, that of someone coined by the media as \"Buffalo Bill\" (Ted Levine), who has so far killed five victims, all located in the eastern U.S., all young women, who are slightly overweight (especially around the hips), all who were drowned in natural bodies of water, and all who ...",
    "synopsis": "F.B.I. trainee Clarice Starling (Jodie Foster) works hard to advance her career, while trying to hide or put behind her West Virginia roots, of which if some knew, would automatically classify her as being backward or white trash. After graduation, she aspires to work in the agency's Behavioral Science Unit under the leadership of Jack Crawford (Scott Glenn). While she is still a trainee, Crawford asks her to question Dr. Hannibal Lecter (Sir Anthony Hopkins), a psychiatrist imprisoned, thus far, for eight years in maximum security isolation for being a serial killer who cannibalized his victims. Clarice is able to figure out the assignment is to pick Lecter's brains to help them solve another serial murder case, that of someone coined by the media as \"Buffalo Bill\" (Ted Levine), who has so far killed five victims, all located in the eastern U.S., all young women, who are slightly overweight (especially around the hips), all who were drowned in natural bodies of water, and all who ...",
    "yt_trailer_code": "8xWbc_kFus4",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/The_Silence_of_the_Lambs_1991/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/The_Silence_of_the_Lambs_1991/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/The_Silence_of_the_Lambs_1991/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/The_Silence_of_the_Lambs_1991/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/The_Silence_of_the_Lambs_1991/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/78A97E995741AD23F9364D3A52BA0A9182453C38",
    "hash": "78A97E995741AD23F9364D3A52BA0A9182453C38",
    "quality": "720p",
    "type": "bluray",
    "seeds": 207,
    "peers": 56,
    "size": "751.84 MB",
    "size_bytes": 788361380,
    "date_uploaded": "2015-11-01 03:20:46",
    "date_uploaded_unix": 1446344446
    },
    {
    "url": "https://yts.lt/torrent/download/B6EC2A4507B13ADE6BC4A1FAC5B39CA25888B326",
    "hash": "B6EC2A4507B13ADE6BC4A1FAC5B39CA25888B326",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 236,
    "peers": 42,
    "size": "1.50 GB",
    "size_bytes": 1610612736,
    "date_uploaded": "2015-11-01 03:20:48",
    "date_uploaded_unix": 1446344448
    }
    ],
    "date_uploaded": "2015-11-01 03:20:46",
    "date_uploaded_unix": 1446344446
    },
    {
    "id": 4320,
    "url": "https://yts.lt/movie/stop-making-sense-1984",
    "imdb_code": "tt0088178",
    "title": "Stop Making Sense",
    "title_english": "Stop Making Sense",
    "title_long": "Stop Making Sense (1984)",
    "slug": "stop-making-sense-1984",
    "year": 1984,
    "rating": 8.6,
    "runtime": 88,
    "genres": [
    "Action",
    "Documentary",
    "Music"
    ],
    "summary": "David Byrne walks onto the stage and does a solo \"Psycho Killer.\" Jerry Harrison, Tina Weymouth and Chris Frantz join him for two more songs. The crew is busy, still setting up. Then, three more musicians and two back-up singers join the band. Everybody sings, plays, harmonizes, dances, and runs. They change instruments and clothes. Bryne appears in the Big Suit. The backdrop is often black, but sometimes it displays words, images, or children's drawings. The band cooks for 18 songs, the lyrics are clear, the house rocks. In this concert film, the Talking Heads hardly talk, don't stop, and always make sense.",
    "description_full": "David Byrne walks onto the stage and does a solo \"Psycho Killer.\" Jerry Harrison, Tina Weymouth and Chris Frantz join him for two more songs. The crew is busy, still setting up. Then, three more musicians and two back-up singers join the band. Everybody sings, plays, harmonizes, dances, and runs. They change instruments and clothes. Bryne appears in the Big Suit. The backdrop is often black, but sometimes it displays words, images, or children's drawings. The band cooks for 18 songs, the lyrics are clear, the house rocks. In this concert film, the Talking Heads hardly talk, don't stop, and always make sense.",
    "synopsis": "David Byrne walks onto the stage and does a solo \"Psycho Killer.\" Jerry Harrison, Tina Weymouth and Chris Frantz join him for two more songs. The crew is busy, still setting up. Then, three more musicians and two back-up singers join the band. Everybody sings, plays, harmonizes, dances, and runs. They change instruments and clothes. Bryne appears in the Big Suit. The backdrop is often black, but sometimes it displays words, images, or children's drawings. The band cooks for 18 songs, the lyrics are clear, the house rocks. In this concert film, the Talking Heads hardly talk, don't stop, and always make sense.",
    "yt_trailer_code": "eUg7-mjW_kk",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/stop_making_sense_1984/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/stop_making_sense_1984/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/stop_making_sense_1984/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/stop_making_sense_1984/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/stop_making_sense_1984/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/2D05028C328CD7062E49E942FC918753660A8803",
    "hash": "2D05028C328CD7062E49E942FC918753660A8803",
    "quality": "720p",
    "type": "bluray",
    "seeds": 6,
    "peers": 0,
    "size": "767.78 MB",
    "size_bytes": 805075681,
    "date_uploaded": "2018-03-07 19:35:46",
    "date_uploaded_unix": 1520447746
    },
    {
    "url": "https://yts.lt/torrent/download/FAC3137AE583C4370C546E405B3F2153F6B2F66B",
    "hash": "FAC3137AE583C4370C546E405B3F2153F6B2F66B",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 30,
    "peers": 3,
    "size": "1.24 GB",
    "size_bytes": 1331439862,
    "date_uploaded": "2015-11-07 21:13:25",
    "date_uploaded_unix": 1446927205
    }
    ],
    "date_uploaded": "2018-03-07 19:35:46",
    "date_uploaded_unix": 1520447746
    },
    {
    "id": 4713,
    "url": "https://yts.lt/movie/seven-samurai-1954",
    "imdb_code": "tt0047478",
    "title": "Seven Samurai",
    "title_english": "Seven Samurai",
    "title_long": "Seven Samurai (1954)",
    "slug": "seven-samurai-1954",
    "year": 1954,
    "rating": 8.6,
    "runtime": 207,
    "genres": [
    "Action",
    "Adventure",
    "Drama"
    ],
    "summary": "A veteran samurai, who has fallen on hard times, answers a village's request for protection from bandits. He gathers 6 other samurai to help him, and they teach the townspeople how to defend themselves, and they supply the samurai with three small meals a day. The film culminates in a giant battle when 40 bandits attack the village.",
    "description_full": "A veteran samurai, who has fallen on hard times, answers a village's request for protection from bandits. He gathers 6 other samurai to help him, and they teach the townspeople how to defend themselves, and they supply the samurai with three small meals a day. The film culminates in a giant battle when 40 bandits attack the village.",
    "synopsis": "A veteran samurai, who has fallen on hard times, answers a village's request for protection from bandits. He gathers 6 other samurai to help him, and they teach the townspeople how to defend themselves, and they supply the samurai with three small meals a day. The film culminates in a giant battle when 40 bandits attack the village.",
    "yt_trailer_code": "h1JziA0nNkQ",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/seven_samurai_1954/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/seven_samurai_1954/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/seven_samurai_1954/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/seven_samurai_1954/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/seven_samurai_1954/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/A755DADFEBB4435FC9AB9564F5F6EC97FD1D02FA",
    "hash": "A755DADFEBB4435FC9AB9564F5F6EC97FD1D02FA",
    "quality": "720p",
    "type": "bluray",
    "seeds": 46,
    "peers": 5,
    "size": "1.65 GB",
    "size_bytes": 1771674010,
    "date_uploaded": "2018-04-27 18:54:57",
    "date_uploaded_unix": 1524848097
    },
    {
    "url": "https://yts.lt/torrent/download/922D55B4329270676174C532BE039C6FC0D64BF4",
    "hash": "922D55B4329270676174C532BE039C6FC0D64BF4",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 61,
    "peers": 12,
    "size": "3.25 GB",
    "size_bytes": 3489660928,
    "date_uploaded": "2018-04-27 22:50:01",
    "date_uploaded_unix": 1524862201
    }
    ],
    "date_uploaded": "2018-04-27 18:54:57",
    "date_uploaded_unix": 1524848097
    },
    {
    "id": 5023,
    "url": "https://yts.lt/movie/porcupine-tree-anesthetize-2010",
    "imdb_code": "tt1626645",
    "title": "Porcupine Tree: Anesthetize",
    "title_english": "Porcupine Tree: Anesthetize",
    "title_long": "Porcupine Tree: Anesthetize (2010)",
    "slug": "porcupine-tree-anesthetize-2010",
    "year": 2010,
    "rating": 8.6,
    "runtime": 130,
    "genres": [
    "Action",
    "Documentary",
    "Music"
    ],
    "summary": "Anesthetize is the second live DVD by progressive rock band Porcupine Tree, released on 20 May 2010. The Blu-ray edition was released on 15 June.",
    "description_full": "Anesthetize is the second live DVD by progressive rock band Porcupine Tree, released on 20 May 2010. The Blu-ray edition was released on 15 June.",
    "synopsis": "Anesthetize is the second live DVD by progressive rock band Porcupine Tree, released on 20 May 2010. The Blu-ray edition was released on 15 June.",
    "yt_trailer_code": "8SNpqgRz3oU",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/porcupine_tree_anesthetize_2010/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/porcupine_tree_anesthetize_2010/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/porcupine_tree_anesthetize_2010/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/porcupine_tree_anesthetize_2010/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/porcupine_tree_anesthetize_2010/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/3C20A0F9D2A8B7E5B0FC06E2FB2D2736C579B230",
    "hash": "3C20A0F9D2A8B7E5B0FC06E2FB2D2736C579B230",
    "quality": "720p",
    "type": "bluray",
    "seeds": 6,
    "peers": 0,
    "size": "976.32 MB",
    "size_bytes": 1023745720,
    "date_uploaded": "2016-01-30 06:50:09",
    "date_uploaded_unix": 1454133009
    },
    {
    "url": "https://yts.lt/torrent/download/589E17D08D2DF75FB62B1BEA4669DAAEDA4DD2BE",
    "hash": "589E17D08D2DF75FB62B1BEA4669DAAEDA4DD2BE",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 14,
    "peers": 4,
    "size": "2 GB",
    "size_bytes": 2147483648,
    "date_uploaded": "2016-01-30 11:29:47",
    "date_uploaded_unix": 1454149787
    }
    ],
    "date_uploaded": "2016-01-30 06:50:09",
    "date_uploaded_unix": 1454133009
    },
    {
    "id": 7667,
    "url": "https://yts.lt/movie/spirited-away-2001",
    "imdb_code": "tt0245429",
    "title": "Spirited Away",
    "title_english": "Spirited Away",
    "title_long": "Spirited Away (2001)",
    "slug": "spirited-away-2001",
    "year": 2001,
    "rating": 8.6,
    "runtime": 125,
    "genres": [
    "Adventure",
    "Animation",
    "Family",
    "Fantasy",
    "Mystery"
    ],
    "summary": "Chihiro and her parents are moving to a small Japanese town in the countryside, much to Chihiro's dismay. On the way to their new home, Chihiro's father makes a wrong turn and drives down a lonely one-lane road which dead-ends in front of a tunnel. Her parents decide to stop the car and explore the area. They go through the tunnel and find an abandoned amusement park on the other side, with its own little town. When her parents see a restaurant with great-smelling food but no staff, they decide to eat and pay later. However, Chihiro refuses to eat and decides to explore the theme park a bit more. She meets a boy named Haku who tells her that Chihiro and her parents are in danger, and they must leave immediately. She runs to the restaurant and finds that her parents have turned into pigs. In addition, the theme park turns out to be a town inhabited by demons, spirits, and evil gods. At the center of the town is a bathhouse where these creatures go to relax. The owner of the bathhouse ...",
    "description_full": "Chihiro and her parents are moving to a small Japanese town in the countryside, much to Chihiro's dismay. On the way to their new home, Chihiro's father makes a wrong turn and drives down a lonely one-lane road which dead-ends in front of a tunnel. Her parents decide to stop the car and explore the area. They go through the tunnel and find an abandoned amusement park on the other side, with its own little town. When her parents see a restaurant with great-smelling food but no staff, they decide to eat and pay later. However, Chihiro refuses to eat and decides to explore the theme park a bit more. She meets a boy named Haku who tells her that Chihiro and her parents are in danger, and they must leave immediately. She runs to the restaurant and finds that her parents have turned into pigs. In addition, the theme park turns out to be a town inhabited by demons, spirits, and evil gods. At the center of the town is a bathhouse where these creatures go to relax. The owner of the bathhouse ...",
    "synopsis": "Chihiro and her parents are moving to a small Japanese town in the countryside, much to Chihiro's dismay. On the way to their new home, Chihiro's father makes a wrong turn and drives down a lonely one-lane road which dead-ends in front of a tunnel. Her parents decide to stop the car and explore the area. They go through the tunnel and find an abandoned amusement park on the other side, with its own little town. When her parents see a restaurant with great-smelling food but no staff, they decide to eat and pay later. However, Chihiro refuses to eat and decides to explore the theme park a bit more. She meets a boy named Haku who tells her that Chihiro and her parents are in danger, and they must leave immediately. She runs to the restaurant and finds that her parents have turned into pigs. In addition, the theme park turns out to be a town inhabited by demons, spirits, and evil gods. At the center of the town is a bathhouse where these creatures go to relax. The owner of the bathhouse ...",
    "yt_trailer_code": "ByXuk9QqQkk",
    "language": "English",
    "mpa_rating": "PG",
    "background_image": "https://yts.lt/assets/images/movies/spirited_away_2001/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/spirited_away_2001/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/spirited_away_2001/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/spirited_away_2001/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/spirited_away_2001/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/C0B8838D4A6DB57C1A7AE44968B892C69974F709",
    "hash": "C0B8838D4A6DB57C1A7AE44968B892C69974F709",
    "quality": "720p",
    "type": "bluray",
    "seeds": 146,
    "peers": 40,
    "size": "1.04 GB",
    "size_bytes": 1116691497,
    "date_uploaded": "2018-04-26 01:20:48",
    "date_uploaded_unix": 1524698448
    },
    {
    "url": "https://yts.lt/torrent/download/661B5355FBF1CD8070C98361F47B17DE32EC0D77",
    "hash": "661B5355FBF1CD8070C98361F47B17DE32EC0D77",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 195,
    "peers": 46,
    "size": "2 GB",
    "size_bytes": 2147483648,
    "date_uploaded": "2018-04-26 03:15:57",
    "date_uploaded_unix": 1524705357
    }
    ],
    "date_uploaded": "2018-04-26 01:20:48",
    "date_uploaded_unix": 1524698448
    },
    {
    "id": 7679,
    "url": "https://yts.lt/movie/city-of-god-2002",
    "imdb_code": "tt0317248",
    "title": "City of God",
    "title_english": "City of God",
    "title_long": "City of God (2002)",
    "slug": "city-of-god-2002",
    "year": 2002,
    "rating": 8.6,
    "runtime": 130,
    "genres": [
    "Crime",
    "Drama"
    ],
    "summary": "Brazil, 1960s, City of God. The Tender Trio robs motels and gas trucks. Younger kids watch and learn well...too well. 1970s: Li'l Zé has prospered very well and owns the city. He causes violence and fear as he wipes out rival gangs without mercy. His best friend Bené is the only one to keep him on the good side of sanity. Rocket has watched these two gain power for years, and he wants no part of it. Yet he keeps getting swept up in the madness. All he wants to do is take pictures. 1980s: Things are out of control between the last two remaining gangs...will it ever end? Welcome to the City of God.",
    "description_full": "Brazil, 1960s, City of God. The Tender Trio robs motels and gas trucks. Younger kids watch and learn well...too well. 1970s: Li'l Zé has prospered very well and owns the city. He causes violence and fear as he wipes out rival gangs without mercy. His best friend Bené is the only one to keep him on the good side of sanity. Rocket has watched these two gain power for years, and he wants no part of it. Yet he keeps getting swept up in the madness. All he wants to do is take pictures. 1980s: Things are out of control between the last two remaining gangs...will it ever end? Welcome to the City of God.",
    "synopsis": "Brazil, 1960s, City of God. The Tender Trio robs motels and gas trucks. Younger kids watch and learn well...too well. 1970s: Li'l Zé has prospered very well and owns the city. He causes violence and fear as he wipes out rival gangs without mercy. His best friend Bené is the only one to keep him on the good side of sanity. Rocket has watched these two gain power for years, and he wants no part of it. Yet he keeps getting swept up in the madness. All he wants to do is take pictures. 1980s: Things are out of control between the last two remaining gangs...will it ever end? Welcome to the City of God.",
    "yt_trailer_code": "ioUE_5wpg_E",
    "language": "English",
    "mpa_rating": "R",
    "background_image": "https://yts.lt/assets/images/movies/city_of_god_2002/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/city_of_god_2002/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/city_of_god_2002/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/city_of_god_2002/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/city_of_god_2002/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/ED567D8C5AAC0B417DE9AECEEDD3AD76C32F1C31",
    "hash": "ED567D8C5AAC0B417DE9AECEEDD3AD76C32F1C31",
    "quality": "720p",
    "type": "bluray",
    "seeds": 65,
    "peers": 20,
    "size": "1.07 GB",
    "size_bytes": 1148903752,
    "date_uploaded": "2018-04-28 08:15:25",
    "date_uploaded_unix": 1524896125
    },
    {
    "url": "https://yts.lt/torrent/download/86A338246204A48D75985861817BF56F9E3E18E9",
    "hash": "86A338246204A48D75985861817BF56F9E3E18E9",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 66,
    "peers": 16,
    "size": "2.07 GB",
    "size_bytes": 2222645576,
    "date_uploaded": "2018-04-28 10:43:44",
    "date_uploaded_unix": 1524905024
    }
    ],
    "date_uploaded": "2018-04-28 08:15:25",
    "date_uploaded_unix": 1524896125
    },
    {
    "id": 11491,
    "url": "https://yts.lt/movie/baraka-1992",
    "imdb_code": "tt0103767",
    "title": "Baraka",
    "title_english": "Baraka",
    "title_long": "Baraka (1992)",
    "slug": "baraka-1992",
    "year": 1992,
    "rating": 8.6,
    "runtime": 96,
    "genres": [
    "Documentary"
    ],
    "summary": "Without words, cameras show us the world, with an emphasis not on \"where,\" but on \"what's there.\" It begins with morning, natural landscapes and people at prayer: volcanoes, water falls, veldts, and forests; several hundred Balinese Hindu men perform kecak, the monkey chant. Indigenous peoples apply body paint; whole villages dance. The film moves to destruction of nature via logging, blasting, and strip mining. Images of poverty, rapid urban life, and factories give way to war, concentration camps, and mass graves. Ancient ruins come into view, and then a sacred river where pilgrims bathe and funeral pyres burn. Prayer and nature return. A monk rings a huge bell; stars wheel across the sky.",
    "description_full": "Without words, cameras show us the world, with an emphasis not on \"where,\" but on \"what's there.\" It begins with morning, natural landscapes and people at prayer: volcanoes, water falls, veldts, and forests; several hundred Balinese Hindu men perform kecak, the monkey chant. Indigenous peoples apply body paint; whole villages dance. The film moves to destruction of nature via logging, blasting, and strip mining. Images of poverty, rapid urban life, and factories give way to war, concentration camps, and mass graves. Ancient ruins come into view, and then a sacred river where pilgrims bathe and funeral pyres burn. Prayer and nature return. A monk rings a huge bell; stars wheel across the sky.",
    "synopsis": "Without words, cameras show us the world, with an emphasis not on \"where,\" but on \"what's there.\" It begins with morning, natural landscapes and people at prayer: volcanoes, water falls, veldts, and forests; several hundred Balinese Hindu men perform kecak, the monkey chant. Indigenous peoples apply body paint; whole villages dance. The film moves to destruction of nature via logging, blasting, and strip mining. Images of poverty, rapid urban life, and factories give way to war, concentration camps, and mass graves. Ancient ruins come into view, and then a sacred river where pilgrims bathe and funeral pyres burn. Prayer and nature return. A monk rings a huge bell; stars wheel across the sky.",
    "yt_trailer_code": "QcVmt5je88M",
    "language": "English",
    "mpa_rating": "",
    "background_image": "https://yts.lt/assets/images/movies/baraka_1992/background.jpg",
    "background_image_original": "https://yts.lt/assets/images/movies/baraka_1992/background.jpg",
    "small_cover_image": "https://yts.lt/assets/images/movies/baraka_1992/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/baraka_1992/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/baraka_1992/large-cover.jpg",
    "state": "ok",
    "torrents": [
    {
    "url": "https://yts.lt/torrent/download/E1AB6327A258A2B37638BE7733B20BC55C992742",
    "hash": "E1AB6327A258A2B37638BE7733B20BC55C992742",
    "quality": "720p",
    "type": "bluray",
    "seeds": 7,
    "peers": 0,
    "size": "860.64 MB",
    "size_bytes": 902446449,
    "date_uploaded": "2019-04-09 21:46:41",
    "date_uploaded_unix": 1554839201
    },
    {
    "url": "https://yts.lt/torrent/download/F72CBCAA426AFBCAC7F0F1DBB9639ABBDE3B42C7",
    "hash": "F72CBCAA426AFBCAC7F0F1DBB9639ABBDE3B42C7",
    "quality": "1080p",
    "type": "bluray",
    "seeds": 30,
    "peers": 4,
    "size": "1.59 GB",
    "size_bytes": 1707249500,
    "date_uploaded": "2019-04-09 23:20:23",
    "date_uploaded_unix": 1554844823
    }
    ],
    "date_uploaded": "2019-04-09 21:46:41",
    "date_uploaded_unix": 1554839201
    }
    ]
    },
    "@meta": {
    "server_time": 1573564541,
    "server_timezone": "CET",
    "api_version": 2,
    "execution_time": "0.01 ms"
    }
    }